import React,{useEffect,useMemo,useRef,useState} from 'react';
import {
 Home,ClipboardList,Search,Car,Users,CalendarDays,Wrench,CreditCard,Megaphone,
 BarChart3,FileText,BadgeCheck,Settings,History,LayoutDashboard,LogOut,RefreshCw,
 ChevronRight,Lock,Unlock,Save,Upload,Download,RotateCcw,Send,Pause,Play,Eye,EyeOff,
 Monitor,Tablet,X,Check,AlertTriangle,Sun,Moon,ChevronDown,Globe2,Plus,Trash2,Pencil,Image as ImageIcon,Link2
} from 'lucide-react';
import {desktopLocales,desktopLocaleLabels,desktopLocaleNames,desktopT,normalizeDesktopLocale,type DesktopLocale} from '../../../desktopLocales';
import {api,post} from '../../api/desktopApi';
import {money,dt} from '../../format';
import type {Role,Bootstrap,Page} from '../../types/desktop';
import {Panel} from '../../components/Panel';
export function Broadcasts({boot,locale}:{boot:Bootstrap;locale:DesktopLocale}){
 const t=(uk:string,pl:string,en:string,de:string,fr:string)=>({uk,pl,en,de,fr}[locale]||en);
 const canForced=boot.user.role==='OWNER'||!!boot.permissions.broadcast_forced_access;
 const [campaigns,setCampaigns]=useState<any[]>([]),[recipients,setRecipients]=useState<any[]>([]),[recipientSearch,setRecipientSearch]=useState(''),[photoPreview,setPhotoPreview]=useState(''),[photoUploading,setPhotoUploading]=useState(false),[form,setForm]=useState<any>({type:'STANDARD',text:'',photoFileId:'',audience:{type:'all'},repeatType:'ONCE',repeatInterval:1,sendNow:true}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[confirmForced,setConfirmForced]=useState(false),[deletingId,setDeletingId]=useState<number|null>(null);
 const load=()=>api('/api/desktop/campaigns').then(d=>setCampaigns(d.campaigns||[]));const loadRecipients=()=>api('/api/desktop/campaign-recipients').then(d=>setRecipients(d.recipients||[])).catch(()=>setRecipients([]));useEffect(()=>{load();loadRecipients()},[]);
 const actuallyCreate=async()=>{setMsg('');setBusy(true);try{const d=await post('/api/desktop/campaigns',form);const sent=Number(d.campaign?.sent_count||0),failed=Number(d.campaign?.failed_count||0),skipped=Number(d.campaign?.skipped_dnd_count||0);setMsg(form.sendNow?t('Відправка виконана','Wysyłka wykonana','Broadcast processed','Versand verarbeitet','Diffusion traitée')+` · ${sent}/${d.recipients}${failed?' · помилки '+failed:''}${skipped?' · DND '+skipped:''}`:t('Кампанію створено','Kampania utworzona','Campaign created','Kampagne erstellt','Campagne créée')+' · '+d.recipients);setForm({...form,text:'',photoFileId:''});setPhotoPreview('');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false);setConfirmForced(false)}};
 const create=async()=>{if(form.type==='SYSTEM'){if(!canForced){setMsg(t('Немає права на системні розсилки.','Brak uprawnienia do komunikatów systemowych.','System broadcast permission is required.','Berechtigung für Systemmeldungen erforderlich.','Autorisation requise pour les messages système.'));return}setConfirmForced(true);return}await actuallyCreate()};
 const action=async(id:number,a:string)=>{await post('/api/desktop/campaigns/'+id,{action:a},'PATCH');load()};
 const uploadBroadcastPhoto=async(file?:File)=>{if(!file)return;if(file.size>5*1024*1024){setMsg(t('Фото завелике. Максимум 5 МБ.','Zdjęcie jest za duże. Maks. 5 MB.','Photo is too large. Maximum 5 MB.','Foto ist zu groß. Maximal 5 MB.','Photo trop volumineuse. 5 Mo maximum.'));return}setPhotoUploading(true);setMsg('');try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});setPhotoPreview(dataUrl);const d=await post('/api/desktop/campaigns/photo',{dataUrl,fileName:file.name});setForm((x:any)=>({...x,photoFileId:d.fileId}));setMsg(t('Фото додано до розсилки.','Zdjęcie dodano do wysyłki.','Photo attached to broadcast.','Foto zur Kampagne hinzugefügt.','Photo ajoutée à la diffusion.'))}catch(e:any){setPhotoPreview('');setMsg(String(e?.message||e))}finally{setPhotoUploading(false)}};
 const toggleRecipient=(id:number)=>setForm((x:any)=>{const ids=Array.isArray(x.audience?.userIds)?x.audience.userIds.map(Number):[];return {...x,audience:{type:'custom',userIds:ids.includes(id)?ids.filter((v:number)=>v!==id):[...ids,id]}}});
 const removeCampaign=async(id:number)=>{if(!confirm(t('Видалити цю кампанію та її історію відправлень? Цю дію не можна скасувати.','Usunąć tę kampanię i historię wysyłek? Tej operacji nie można cofnąć.','Delete this campaign and its delivery history? This cannot be undone.','Diese Kampagne und ihren Versandverlauf löschen? Dies kann nicht rückgängig gemacht werden.','Supprimer cette campagne et son historique d’envoi ? Cette action est irréversible.')))return;setDeletingId(id);setMsg('');try{await api('/api/desktop/campaigns/'+id,{method:'DELETE'});setCampaigns(rows=>rows.filter(x=>x.id!==id));setMsg(t('Кампанію видалено','Kampania została usunięta','Campaign deleted','Kampagne gelöscht','Campagne supprimée'))}catch(e:any){setMsg(String(e?.message||e))}finally{setDeletingId(null)}};
 const totalSent=campaigns.reduce((s,c)=>s+Number(c.sent_count||0),0),totalFailed=campaigns.reduce((s,c)=>s+Number(c.failed_count||0),0),active=campaigns.filter(c=>['ACTIVE','SCHEDULED'].includes(c.status)).length,totalDnd=campaigns.reduce((s,c)=>s+Number(c.skipped_dnd_count||0),0);
 const audienceNeedsValue=['language','brand','phone','user'].includes(form.audience.type);
 const selectedRecipientIds=(Array.isArray(form.audience?.userIds)?form.audience.userIds:[]).map(Number);const filteredRecipients=useMemo(()=>{const term=recipientSearch.trim().toLowerCase();return recipients.filter(x=>!term||String([x.first_name,x.username,x.telegram_user_id,x.phone_number].join(' ')).toLowerCase().includes(term)).slice(0,80)},[recipients,recipientSearch]);
 return <><div className="broadcast-hero"><div><span className="desk-eyebrow">CLIENT COMMUNICATIONS</span><h2>{t('Розсилки','Wysyłki','Broadcasts','Nachrichten','Diffusions')}</h2><p>{t('Звичайні повідомлення враховують налаштування клієнта. Системні ігнорують лише внутрішній режим «Не турбувати» — обмеження Telegram не обходяться.','Zwykłe wiadomości respektują ustawienia klienta. Systemowe ignorują tylko wewnętrzny tryb DND — ograniczenia Telegrama pozostają.','Normal messages respect client preferences. System messages bypass only the internal DND setting — Telegram restrictions still apply.','Normale Nachrichten beachten Kundeneinstellungen. Systemmeldungen umgehen nur den internen DND-Modus.','Les messages normaux respectent les préférences. Les messages système ignorent uniquement le DND interne.')}</p></div><div className="broadcast-stats"><div><b>{active}</b><span>{t('активні','aktywne','active','aktiv','actives')}</span></div><div><b>{totalSent}</b><span>{t('надіслано','wysłane','sent','gesendet','envoyés')}</span></div><div><b>{totalDnd}</b><span>DND</span></div><div><b>{totalFailed}</b><span>{t('помилки','błędy','errors','Fehler','erreurs')}</span></div></div></div>
 <div className="broadcast-layout"><section className="broadcast-composer"><div className="broadcast-card-head"><div><Megaphone/><span><b>{t('Нова кампанія','Nowa kampania','New campaign','Neue Kampagne','Nouvelle campagne')}</b><small>{t('Створити повідомлення клієнтам','Utwórz wiadomość dla klientów','Create a client message','Kundennachricht erstellen','Créer un message client')}</small></span></div><span className={'broadcast-type '+String(form.type).toLowerCase()}>{form.type==='SYSTEM'?t('СИСТЕМНА','SYSTEMOWA','SYSTEM','SYSTEM','SYSTÈME'):t('ЗВИЧАЙНА','ZWYKŁA','NORMAL','NORMAL','NORMALE')}</span></div>
 <div className="broadcast-type-cards"><button className={form.type==='STANDARD'?'active':''} onClick={()=>setForm({...form,type:'STANDARD'})}><span/><div><b>{t('Звичайне','Zwykłe','Normal','Normal','Normal')}</b><small>{t('Враховує налаштування сповіщень користувача','Uwzględnia ustawienia powiadomień','Respects user notification preferences','Berücksichtigt Benachrichtigungseinstellungen','Respecte les préférences de notification')}</small></div></button><button className={form.type==='SYSTEM'?'active system':''} disabled={!canForced} onClick={()=>canForced&&setForm({...form,type:'SYSTEM'})}><span/><div><b>{t('Системне','Systemowe','System','System','Système')}</b><small>{t('Надсилається незалежно від внутрішнього «Не турбувати»','Ignoruje wewnętrzny tryb DND','Ignores internal DND','Ignoriert internes DND','Ignore le DND interne')}</small></div></button></div>
 <div className="broadcast-form-grid"><label><span>{t('Аудиторія','Odbiorcy','Audience','Zielgruppe','Audience')}</span><select value={form.audience.type} onChange={e=>setForm({...form,audience:{type:e.target.value}})}><option value="all">{t('Усі клієнти','Wszyscy klienci','All clients','Alle Kunden','Tous les clients')}</option><option value="active">{t('Активні','Aktywni','Active','Aktive','Actifs')}</option><option value="new">{t('Нові','Nowi','New','Neu','Nouveaux')}</option><option value="returning">{t('Постійні','Powracający','Returning','Wiederkehrend','Fidèles')}</option><option value="vip">VIP</option><option value="active_order">{t('З активним замовленням','Z aktywnym zleceniem','Active order','Mit aktivem Auftrag','Commande active')}</option><option value="completed">{t('З завершеними замовленнями','Z zakończonymi zleceniami','Completed orders','Abgeschlossene Aufträge','Commandes terminées')}</option><option value="language">{t('За мовою','Według języka','By language','Nach Sprache','Par langue')}</option><option value="brand">{t('За маркою авто','Według marki auta','By car brand','Nach Automarke','Par marque')}</option><option value="user">{t('Окремий користувач','Konkretny użytkownik','Specific user','Bestimmter Nutzer','Utilisateur précis')}</option><option value="custom">{t('Вибрані користувачі','Wybrani użytkownicy','Selected users','Ausgewählte Nutzer','Utilisateurs sélectionnés')}</option></select></label>{audienceNeedsValue&&<label><span>{form.audience.type==='language'?t('Мова','Język','Language','Sprache','Langue'):t('Значення','Wartość','Value','Wert','Valeur')}</span>{form.audience.type==='language'?<select value={form.audience.value||'uk'} onChange={e=>setForm({...form,audience:{...form.audience,value:e.target.value}})}>{desktopLocales.map(l=><option value={l} key={l}>{desktopLocaleNames[l]}</option>)}</select>:<input value={form.audience.value||''} onChange={e=>setForm({...form,audience:{...form.audience,value:e.target.value}})} placeholder={form.audience.type==='user'?'@username / Telegram ID':'Audi / +380…'}/>}</label>}</div>
 {form.audience.type==='custom'&&<div className="broadcast-recipient-picker"><div className="broadcast-recipient-head"><label><Search/><input value={recipientSearch} onChange={e=>setRecipientSearch(e.target.value)} placeholder={t('Пошук клієнта…','Szukaj klienta…','Search client…','Kunde suchen…','Rechercher un client…')}/></label><span>{t('Обрано','Wybrano','Selected','Ausgewählt','Sélectionnés')}: <b>{selectedRecipientIds.length}</b></span></div><div className="broadcast-recipient-list">{filteredRecipients.map(x=><button type="button" key={x.id} className={selectedRecipientIds.includes(Number(x.id))?'selected':''} onClick={()=>toggleRecipient(Number(x.id))}><span className="recipient-check">{selectedRecipientIds.includes(Number(x.id))?<Check/>:null}</span><span><b>{x.first_name||x.username||'Client #'+x.id}</b><small>{x.username?'@'+x.username+' · ':''}{x.telegram_user_id}{x.client_tier&&x.client_tier!=='STANDARD'?' · '+x.client_tier:''}</small></span></button>)}</div>{!recipients.length&&<small className="desk-muted">{t('Немає доступних Telegram-користувачів.','Brak dostępnych użytkowników Telegram.','No Telegram users available.','Keine Telegram-Nutzer verfügbar.','Aucun utilisateur Telegram disponible.')}</small>}</div>}
 <label className="broadcast-message"><span>{t('Повідомлення','Wiadomość','Message','Nachricht','Message')}</span><textarea value={form.text} maxLength={3900} onChange={e=>setForm({...form,text:e.target.value})} placeholder={t('Напишіть повідомлення для клієнтів…','Napisz wiadomość…','Write a client message…','Nachricht schreiben…','Écrivez un message…')}/><small>{form.text.length} / 3900</small></label>
 <div className="broadcast-photo-upload"><div className="broadcast-photo-copy"><span><ImageIcon/></span><div><b>{t('Фото до повідомлення','Zdjęcie do wiadomości','Message photo','Foto zur Nachricht','Photo du message')}</b><small>{t('JPG, PNG або WEBP · до 5 МБ','JPG, PNG lub WEBP · do 5 MB','JPG, PNG or WEBP · up to 5 MB','JPG, PNG oder WEBP · bis 5 MB','JPG, PNG ou WEBP · 5 Mo max.')}</small></div></div>{photoPreview?<div className="broadcast-photo-preview"><img src={photoPreview} alt=""/><button type="button" onClick={()=>{setPhotoPreview('');setForm({...form,photoFileId:''})}}><X/></button></div>:<label className="broadcast-photo-picker"><Upload/><span>{photoUploading?t('Завантажую…','Przesyłam…','Uploading…','Lädt…','Téléversement…'):t('Обрати фото','Wybierz zdjęcie','Choose photo','Foto wählen','Choisir une photo')}</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={photoUploading} onChange={e=>{void uploadBroadcastPhoto(e.target.files?.[0]);e.currentTarget.value=''}}/></label>}<details className="broadcast-photo-advanced"><summary>{t('Вже маєте Telegram file_id?','Masz Telegram file_id?','Already have a Telegram file_id?','Telegram file_id vorhanden?','Vous avez déjà un file_id Telegram ?')}</summary><input value={form.photoFileId||''} onChange={e=>setForm({...form,photoFileId:e.target.value})} placeholder="AgACAg..."/></details></div>
 <div className="broadcast-schedule"><div className="broadcast-send-mode"><button className={form.sendNow?'active':''} onClick={()=>setForm({...form,sendNow:true})}><Send/>{t('Зараз','Teraz','Now','Jetzt','Maintenant')}</button><button className={!form.sendNow?'active':''} onClick={()=>setForm({...form,sendNow:false})}><CalendarDays/>{t('Запланувати','Zaplanuj','Schedule','Planen','Planifier')}</button></div>{!form.sendNow&&<input type="datetime-local" value={form.scheduleAt||''} onChange={e=>setForm({...form,scheduleAt:e.target.value})}/>}</div>
 <details className="broadcast-repeat"><summary>{t('Повторення кампанії','Powtarzanie kampanii','Campaign recurrence','Wiederholung','Récurrence')}</summary><div><label><span>{t('Період','Okres','Period','Zeitraum','Période')}</span><select value={form.repeatType} onChange={e=>setForm({...form,repeatType:e.target.value})}><option>ONCE</option><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option><option>CUSTOM</option></select></label><label><span>{t('Інтервал','Interwał','Interval','Intervall','Intervalle')}</span><input type="number" min="1" value={form.repeatInterval} onChange={e=>setForm({...form,repeatInterval:Number(e.target.value)})}/></label></div></details>
 <button className="broadcast-submit" onClick={create} disabled={busy||photoUploading||!form.text.trim()||(form.audience.type==='custom'&&selectedRecipientIds.length===0)}><Send/>{busy?t('Запускаю…','Uruchamiam…','Starting…','Starte…','Démarrage…'):form.sendNow?t('Запустити розсилку','Uruchom wysyłkę','Start broadcast','Nachricht starten','Lancer la diffusion'):t('Запланувати кампанію','Zaplanuj kampanię','Schedule campaign','Kampagne planen','Planifier la campagne')}</button>{msg&&<div className="broadcast-feedback">{msg}</div>}</section>
 <section className="broadcast-history"><div className="broadcast-history-head"><div><b>{t('Історія кампаній','Historia kampanii','Campaign history','Kampagnenverlauf','Historique')}</b><span>{campaigns.length}</span></div><button className="panel-icon-btn" onClick={load}><RefreshCw/></button></div><div className="broadcast-timeline">{campaigns.length===0?<div className="broadcast-empty"><Megaphone/><b>{t('Ще немає кампаній','Brak kampanii','No campaigns yet','Noch keine Kampagnen','Aucune campagne')}</b></div>:campaigns.map(c=><article key={c.id}><div className="broadcast-dot"/><div className="broadcast-item-main"><div className="broadcast-item-title"><b>#{c.id} · {c.type}</b><span className={'campaign-status '+String(c.status).toLowerCase()}>{c.status}</span></div><p>{c.text}</p><div className="broadcast-metrics"><span>👥 {c.recipient_count||0}</span><span>✓ {c.sent_count||0}</span><span>DND {c.skipped_dnd_count||0}</span><span>🚫 {c.blocked_count||0}</span><span>TG {c.telegram_error_count||0}</span><span>⚠ {c.other_error_count||0}</span><span>{dt(c.created_at)}</span></div></div><div className="desk-inline-actions"><button title="Pause" aria-label="Pause" onClick={()=>action(c.id,'pause')}><Pause/></button><button title="Resume" aria-label="Resume" onClick={()=>action(c.id,'resume')}><Play/></button><button title="Send now" aria-label="Send now" onClick={()=>action(c.id,'send_now')}><Send/></button>{boot.user.role!=='MANAGER'&&<button className="broadcast-delete" title={t('Видалити кампанію','Usuń kampanię','Delete campaign','Kampagne löschen','Supprimer la campagne')} aria-label={t('Видалити кампанію','Usuń kampanię','Delete campaign','Kampagne löschen','Supprimer la campagne')} disabled={deletingId===c.id} onClick={()=>removeCampaign(c.id)}><Trash2/></button>}</div></article>)}</div></section></div>
 {confirmForced&&<div className="desk-drawer-backdrop critical-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setConfirmForced(false)}><div className="critical-modal"><AlertTriangle/><h3>{t('Системне повідомлення','Wiadomość systemowa','System message','Systemmeldung','Message système')}</h3><p>{t('Це системне повідомлення буде надіслано також користувачам, які вимкнули звичайні сповіщення. Воно не обходить блокування бота або обмеження Telegram.','Ta wiadomość trafi także do użytkowników z wyłączonymi zwykłymi powiadomieniami. Nie omija blokady bota ani ograniczeń Telegrama.','This system message will also be sent to users who disabled normal notifications. It does not bypass bot blocks or Telegram restrictions.','Diese Systemmeldung wird auch an Nutzer mit deaktivierten normalen Benachrichtigungen gesendet. Telegram-Sperren werden nicht umgangen.','Ce message système sera aussi envoyé aux utilisateurs ayant désactivé les notifications normales. Les restrictions Telegram restent applicables.')}</p><div><button onClick={()=>setConfirmForced(false)}>{t('Скасувати','Anuluj','Cancel','Abbrechen','Annuler')}</button><button className="desk-primary" onClick={actuallyCreate}>{t('Продовжити','Kontynuuj','Continue','Fortfahren','Continuer')}</button></div></div></div>}</>
}

