import type {Env} from './types';import {ensureDb,event,getUserByTelegramId,setSetting,upsertUser} from './db';import {sendMessage,editMessage,tgApi} from './telegram';
const esc=(s='')=>s.replace(/[<&>]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]!));
export async function handleBotUpdate(env:Env,update:any,origin:string){const msg=update.message,cb=update.callback_query;
 if(msg?.from){const owner=String(msg.from.id)===String(env.OWNER_TELEGRAM_ID);const u=await upsertUser(env,msg.from,owner);const role=owner?'OWNER':u.role||'CLIENT';await event(env,u.id,'bot_message',{text:msg.text||'',contact:!!msg.contact});
  if(msg.contact){if(!env.DB)return sendMessage(env,msg.chat.id,'Database is not connected yet.');if(msg.contact.user_id&&Number(msg.contact.user_id)!==Number(msg.from.id))return sendMessage(env,msg.chat.id,'Please share your own Telegram contact.');await ensureDb(env);await env.DB.prepare(`UPDATE client_profiles SET phone_number=?,phone_verified_via_telegram=1,phone_shared_at=CURRENT_TIMESTAMP,preferred_contact_method='TELEGRAM_PHONE' WHERE user_id=?`).bind(msg.contact.phone_number,u.id).run();await event(env,u.id,'phone_shared',{source:'telegram_contact'});return sendMessage(env,msg.chat.id,'✅ Дякуємо. Номер збережено лише для зв’язку щодо ваших заявок.',{remove_keyboard:true})}
  const text=(msg.text||'').trim();if(text==='/start phone'||text==='/phone'||text==='/start support')return requestPhone(env,msg.chat.id);
  if(text.startsWith('/start')||text==='/app')return menu(env,msg.chat.id,role,origin,msg.from.first_name);if(text==='/help')return sendMessage(env,msg.chat.id,help(role));if(text==='/panel'&&['OWNER','ADMIN','MANAGER'].includes(role))return panel(env,msg.chat.id,role);if(text==='/stats'&&['OWNER','ADMIN'].includes(role))return stats(env,msg.chat.id);
  if(owner&&text.startsWith('/workingdays ')){const value=text.slice(13).trim();if(!/^([1-7],?)+$/.test(value))return sendMessage(env,msg.chat.id,'Format: /workingdays 1,2,3,4,5');await setSetting(env,'working_days',value);return sendMessage(env,msg.chat.id,`✅ Working days: ${esc(value)}`)}
  if(owner&&text.startsWith('/workinghours ')){const value=text.slice(14).trim();if(!/^\d{2}:\d{2}-\d{2}:\d{2}$/.test(value))return sendMessage(env,msg.chat.id,'Format: /workinghours 09:00-18:00');await setSetting(env,'working_hours',value);return sendMessage(env,msg.chat.id,`✅ Working hours: ${esc(value)}`)}
  return menu(env,msg.chat.id,role,origin,msg.from.first_name)}
 if(cb?.from){await tgApi(env,'answerCallbackQuery',{callback_query_id:cb.id});const owner=String(cb.from.id)===String(env.OWNER_TELEGRAM_ID);const dbu=await getUserByTelegramId(env,cb.from.id);const role=owner?'OWNER':dbu?.role||'CLIENT';if(!['OWNER','ADMIN','MANAGER'].includes(role)&&String(cb.data||'').startsWith('admin:'))return;const chat=cb.message.chat.id,id=cb.message.message_id;
  if(cb.data==='help')return editMessage(env,chat,id,help(role),{inline_keyboard:[[{text:'⬅️ Menu',callback_data:'menu'}]]});if(cb.data==='menu')return editMessage(env,chat,id,'<b>Chameleon Detailing</b>\nChoose an action.',{inline_keyboard:[[{text:'🦎 Open Mini App',web_app:{url:env.APP_URL||origin}}],...(['OWNER','ADMIN','MANAGER'].includes(role)?[[{text:'⚙️ Staff Panel',callback_data:'admin:panel'}]]:[])]});if(cb.data==='admin:panel')return editPanel(env,chat,id,role);
  if(cb.data==='admin:stats'&&['OWNER','ADMIN'].includes(role)){const text=await statsText(env);return editMessage(env,chat,id,text,{inline_keyboard:[[{text:'⬅️ Panel',callback_data:'admin:panel'}]]})}
  if(cb.data==='admin:services'&&['OWNER','ADMIN'].includes(role)){const text=await servicesText(env);return editMessage(env,chat,id,text,{inline_keyboard:[[{text:'⬅️ Panel',callback_data:'admin:panel'}]]})}
  if(cb.data==='admin:users'){const text=await usersText(env);return editMessage(env,chat,id,text,{inline_keyboard:[[{text:'⬅️ Panel',callback_data:'admin:panel'}]]})}
  if(cb.data==='admin:requests'){const text=await requestsText(env);return editMessage(env,chat,id,text,{inline_keyboard:[[{text:'⬅️ Panel',callback_data:'admin:panel'}]]})}
  if(cb.data==='admin:maintenance'&&role==='OWNER'){if(env.DB){await ensureDb(env);const cur=await env.DB.prepare("SELECT value FROM settings WHERE key='maintenance.enabled'").first<any>();await setSetting(env,'maintenance.enabled',cur?.value==='1'?'0':'1')}return editPanel(env,chat,id,role)}
  if(cb.data==='admin:emergency'&&['OWNER','ADMIN'].includes(role)){if(env.DB){const cur=await env.DB.prepare("SELECT value FROM settings WHERE key='emergency_enabled'").first<any>();await setSetting(env,'emergency_enabled',cur?.value==='1'?'0':'1')}return editPanel(env,chat,id,role)}
 }}
async function requestPhone(env:Env,chat:number){return sendMessage(env,chat,'📱 Якщо хочете, добровільно поділіться номером. Він буде використаний лише для зв’язку щодо деталей замовлення.',{keyboard:[[{text:'📱 Поділитися моїм номером',request_contact:true}],[{text:'Скасувати'}]],resize_keyboard:true,one_time_keyboard:true})}
async function menu(env:Env,chat:number,role:string,origin:string,name:string){const url=env.APP_URL||origin;const rows:any[]=[[{text:'🦎 Open Chameleon Detailing',web_app:{url}}],[{text:'📱 Share phone',url:`https://t.me/${env.BOT_USERNAME}?start=phone`}],[{text:'❓ Help',callback_data:'help'}]];if(['OWNER','ADMIN','MANAGER'].includes(role))rows.push([{text:'⚙️ Staff Panel',callback_data:'admin:panel'}]);return sendMessage(env,chat,`<b>Chameleon Detailing</b>\n\nПривіт, ${esc(name)} ✨\nПреміальний догляд за авто — швидко, прозоро та прямо в Telegram.`,{inline_keyboard:rows})}
const help=(role:string)=>`<b>Help</b>\n/start — main menu\n/app — open Mini App\n/phone — voluntarily share phone\n/help — help\n${['OWNER','ADMIN','MANAGER'].includes(role)?'\n<b>Staff</b>\n/panel — control panel':''}${role==='OWNER'?'\n/workingdays 1,2,3,4,5\n/workinghours 09:00-18:00':''}`;
async function panel(env:Env,chat:number,role:string){return sendMessage(env,chat,'<b>🦎 STAFF PANEL</b>\nRole: '+role,panelKb(role))}
async function editPanel(env:Env,chat:number,id:number,role:string){const m=env.DB?await env.DB.prepare("SELECT value FROM settings WHERE key='maintenance.enabled'").first<any>():null;const e=env.DB?await env.DB.prepare("SELECT value FROM settings WHERE key='emergency_enabled'").first<any>():null;return editMessage(env,chat,id,`<b>🦎 STAFF PANEL</b>\nRole: ${role}\nMaintenance: ${m?.value==='1'?'🔴 ON':'🟢 OFF'}\nEmergency: ${e?.value==='1'?'🟠 ON':'⚪ OFF'}`,panelKb(role))}
const panelKb=(role:string)=>({inline_keyboard:[...(['OWNER','ADMIN'].includes(role)?[[{text:'📊 Analytics',callback_data:'admin:stats'},{text:'🧽 Services',callback_data:'admin:services'}],[{text:'🚨 Emergency',callback_data:'admin:emergency'}]]:[]),...(role==='OWNER'?[[{text:'🛠 Maintenance',callback_data:'admin:maintenance'}]]:[]),[{text:'👥 Users',callback_data:'admin:users'},{text:'🧾 Requests',callback_data:'admin:requests'}]]});
async function statsText(env:Env){if(!env.DB)return '<b>📊 Analytics</b>\nD1 binding is not configured.';await ensureDb(env);const u=await env.DB.prepare('SELECT COUNT(*) c FROM users').first<any>();const r=await env.DB.prepare("SELECT COUNT(*) c FROM service_requests WHERE is_test=0").first<any>();const a=await env.DB.prepare("SELECT COUNT(*) c FROM analytics_events WHERE event_type='calculator_completed'").first<any>();return `<b>📊 Analytics</b>\nUsers: <b>${u?.c||0}</b>\nCalculations: <b>${a?.c||0}</b>\nRequests: <b>${r?.c||0}</b>`}
async function stats(env:Env,chat:number){return sendMessage(env,chat,await statsText(env))}
async function servicesText(env:Env){if(!env.DB)return '<b>🧽 Services</b>\nD1 binding is not configured.';const r=await env.DB.prepare('SELECT slug,enabled FROM services ORDER BY sort_order').all<any>();return '<b>🧽 Services</b>\n'+r.results.map(x=>`${x.enabled?'✅':'❌'} ${esc(x.slug)}`).join('\n')}
async function usersText(env:Env){if(!env.DB)return '<b>👥 Users</b>\nD1 binding is not configured.';const r=await env.DB.prepare('SELECT telegram_user_id,username,first_name,role FROM users ORDER BY id DESC LIMIT 20').all<any>();return '<b>👥 Latest users</b>\n'+(r.results.map(x=>`${x.role==='OWNER'?'👑':'•'} ${esc(x.first_name||'User')} ${x.username?'@'+esc(x.username):''}`).join('\n')||'No users yet')}
async function requestsText(env:Env){if(!env.DB)return '<b>🧾 Requests</b>\nD1 binding is not configured.';const r=await env.DB.prepare('SELECT id,service_slug,status,request_type,calculated_price,currency FROM service_requests ORDER BY id DESC LIMIT 20').all<any>();return '<b>🧾 Latest requests</b>\n'+(r.results.map(x=>`#${x.id} ${esc(x.service_slug)} · ${x.request_type} · ${x.status} · ${x.calculated_price} ${x.currency}`).join('\n')||'No requests yet')}
