import type {Env} from './types';
import {getSetting} from './db';
const parts=(d:Date,tz:string)=>{const fmt=new Intl.DateTimeFormat('en-CA',{timeZone:tz,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false,year:'numeric',month:'2-digit',day:'2-digit'});const o=Object.fromEntries(fmt.formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return {weekday:o.weekday,hour:Number(o.hour),minute:Number(o.minute),date:`${o.year}-${o.month}-${o.day}`}};
const weekdayNumber=(name:string)=>Number(({Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7} as any)[name]||1);
const parseHours=(openTime:string,closeTime:string)=>{const [fh,fm]=openTime.split(':').map(Number),[th,tm]=closeTime.split(':').map(Number);return {from:fh*60+fm,to:th*60+tm}};
async function weeklyRows(env:Env){if(!env.DB)return [] as any[];try{const r=await env.DB.prepare('SELECT day_of_week,enabled,open_time,close_time FROM business_weekly_schedule ORDER BY day_of_week').all<any>();return r.results||[]}catch{return []}}
async function nextWorking(env:Env,now:Date,tz:string,fallbackDays:number[],fallbackHours:string){const rows=await weeklyRows(env);const map=new Map(rows.map((r:any)=>[Number(r.day_of_week),r]));for(let i=0;i<14;i++){const d=new Date(now.getTime()+i*86400000);const p=parts(d,tz);const wd=weekdayNumber(p.weekday);let enabled=fallbackDays.includes(wd);let [openTime,closeTime]=fallbackHours.split('-');const row=map.get(wd);if(row){enabled=Number(row.enabled)===1;openTime=String(row.open_time||openTime);closeTime=String(row.close_time||closeTime)}if(env.DB){const ex=await env.DB.prepare('SELECT is_closed,open_time,close_time FROM schedule_exceptions WHERE date=? LIMIT 1').bind(p.date).first<any>().catch(()=>null);if(ex){if(Number(ex.is_closed)===1)enabled=false;else if(ex.open_time&&ex.close_time){enabled=true;openTime=String(ex.open_time);closeTime=String(ex.close_time)}}}if(!enabled)continue;const {from}=parseHours(openTime||'09:00',closeTime||'18:00');if(i===0&&p.hour*60+p.minute<from){const c=new Date(now.getTime()+Math.max(1,(from-(p.hour*60+p.minute)))*60000);return c.toISOString()}if(i>0){const c=new Date(now.getTime()+i*86400000);c.setUTCHours(Math.floor(from/60),from%60,0,0);return c.toISOString()}}return null}
export async function scheduleState(env:Env,now=new Date()){
 const timezone=await getSetting(env,'business_timezone',env.BUSINESS_TIMEZONE||'Europe/Warsaw');
 const fallbackDays=(await getSetting(env,'working_days','1,2,3,4,5')).split(',').map((x:string)=>Number(x.trim())).filter((x:number)=>x>=1&&x<=7);
 const fallbackHours=await getSetting(env,'working_hours','09:00-18:00');
 const p=parts(now,timezone),wd=weekdayNumber(p.weekday),minutes=p.hour*60+p.minute;
 let enabled=fallbackDays.includes(wd),[openTime,closeTime]=fallbackHours.split('-');
 const rows=await weeklyRows(env),row=rows.find((r:any)=>Number(r.day_of_week)===wd);if(row){enabled=Number(row.enabled)===1;openTime=String(row.open_time||openTime);closeTime=String(row.close_time||closeTime)}
 let isWorkingDay=enabled;const range=parseHours(openTime||'09:00',closeTime||'18:00');let isOpen=isWorkingDay&&minutes>=range.from&&minutes<range.to;
 if(env.DB){const ex=await env.DB.prepare('SELECT is_closed,open_time,close_time FROM schedule_exceptions WHERE date=? LIMIT 1').bind(p.date).first<any>().catch(()=>null);if(ex){if(Number(ex.is_closed)===1){isWorkingDay=false;isOpen=false}else if(ex.open_time&&ex.close_time){isWorkingDay=true;openTime=String(ex.open_time);closeTime=String(ex.close_time);const r=parseHours(openTime,closeTime);isOpen=minutes>=r.from&&minutes<r.to}}}
 const emergencyEnabled=(await getSetting(env,'emergency_enabled','0'))==='1';const multiplier=Math.min(2,Math.max(1.5,Number(await getSetting(env,'emergency_multiplier','1.5'))||1.5));
 return {isOpen,isWorkingDay,nextWorkingAt:isOpen?null:await nextWorking(env,now,timezone,fallbackDays,fallbackHours),emergencyEnabled,emergencyMultiplier:multiplier,timezone,workingHours:`${openTime}-${closeTime}`};
}
