import React,{useEffect,useMemo,useRef,useState} from 'react';
import {
 Home,ClipboardList,Search,Car,Users,CalendarDays,Wrench,CreditCard,Megaphone,
 BarChart3,FileText,BadgeCheck,Settings,History,LayoutDashboard,LogOut,RefreshCw,
 ChevronRight,Lock,Unlock,Save,Upload,Download,RotateCcw,Send,Pause,Play,Eye,EyeOff,
 Monitor,Tablet,X,Check,AlertTriangle,Sun,Moon,ChevronDown,Globe2,Plus,Trash2,Pencil,Image as ImageIcon,Link2
} from 'lucide-react';
import {desktopLocales,desktopLocaleLabels,desktopLocaleNames,desktopT,normalizeDesktopLocale,type DesktopLocale} from '../../../desktopLocales';
import {api,post} from '../../api/desktopApi';
import {money,dt} from '../../format';
import type {Role,Bootstrap,Page} from '../../types/desktop';
import {statusLabel,statusMeta} from '../../config/statusMeta';
import {Drawer,Tabs} from '../../components/primitives';
import {showError} from '../../components/Toast';
import {businessDate,businessTime,fromBusinessLocal} from '../../format';
import {Panel} from '../../components/Panel';
export function OrderDrawer({boot,id,initialTab='overview',close,changed}:{boot:Bootstrap;id:number;initialTab?:string;close:()=>void;changed:()=>void}){
 const validTabs=['overview','services','checklist','photos','payment'];
 const [tab,setTab]=useState(validTabs.includes(initialTab)?initialTab:'overview');
 const [o,setO]=useState<any>(null),[saving,setSaving]=useState(false),[form,setForm]=useState<any>({}),[catalog,setCatalog]=useState<any>({services:[],options:[],extras:[]}),[staffRows,setStaffRows]=useState<any[]>([]),[pickType,setPickType]=useState<'service'|'option'>('service'),[pickId,setPickId]=useState(''),[serviceBusy,setServiceBusy]=useState(false);
 const parseList=(v:any)=>{try{const x=typeof v==='string'?JSON.parse(v):v;return Array.isArray(x)?x.map(String):[]}catch{return []}};
 const load=async()=>{const [d,cat,team]=await Promise.all([api('/api/desktop/orders/'+id),api('/api/desktop/orders/'+id+'/catalog'),api('/api/desktop/staff').catch(()=>({staff:[]}))]);setO(d.order);setCatalog(cat);setStaffRows(team.staff||[]);setForm({status:d.order?.status,paymentStatus:d.order?.payment_status,scheduledFor:d.order?.scheduled_for?businessDate(d.order.scheduled_for)+'T'+businessTime(d.order.scheduled_for):'',estimatedDurationMin:Number(d.order?.estimated_duration_min||60),responsibleStaffId:d.order?.responsible_staff_id||d.order?.assigned_manager_id||'',finalPrice:d.order?.final_job_price??d.order?.calculated_price,staffNote:d.order?.staff_note||'',accelerated:!!d.order?.accelerated,acceleratedSurcharge:d.order?.accelerated_surcharge||0,services:parseList(d.order?.services_json),options:parseList(d.order?.options_json)})};
 useEffect(()=>{load().catch(showError)},[id]);
 useEffect(()=>{setTab(validTabs.includes(initialTab)?initialTab:'overview')},[initialTab,id]);
 const canDeadline=boot.user.role!=='MANAGER'||!!boot.permissions.order_deadline_access;
 const save=async()=>{setSaving(true);try{await post('/api/desktop/orders/'+id+'/catalog-selection',{services:form.services||[],options:form.options||[]},'PATCH');const payload:any={...form,scheduledFor:form.scheduledFor?fromBusinessLocal(form.scheduledFor):null};if(!canDeadline||Number(payload.estimatedDurationMin)===Number(o?.estimated_duration_min||60))delete payload.estimatedDurationMin;await post('/api/desktop/orders/'+id,payload,'PATCH');await load();changed()}finally{setSaving(false)}};
 const addCatalog=async()=>{if(!pickId)return;setServiceBusy(true);try{await post('/api/desktop/orders/'+id+'/services',{catalogType:pickType,serviceId:Number(pickId)});setPickId('');await load();changed()}finally{setServiceBusy(false)}};
 const removeExtra=async(eid:number)=>{setServiceBusy(true);try{await api('/api/desktop/orders/'+id+'/services/'+eid,{method:'DELETE'});await load();changed()}finally{setServiceBusy(false)}};
 const toggleBase=(kind:'services'|'options',slug:string)=>{const list=[...(form[kind]||[])];setForm({...form,[kind]:list.includes(slug)?list.filter((x:string)=>x!==slug):[...list,slug]})};
 const deadlinePreview=(()=>{if(!form.scheduledFor||!Number(form.estimatedDurationMin))return o?.deadline_at||null;const start=Date.parse(fromBusinessLocal(form.scheduledFor));return Number.isFinite(start)?new Date(start+Number(form.estimatedDurationMin)*60000).toISOString():o?.deadline_at||null})();
 const durationLabel=(m:number)=>m>=60?`${Math.floor(m/60)} год${m%60?` ${m%60} хв`:''}`:`${m} хв`;
 return <Drawer title={o?[o.brand,o.model,o.plate].filter(Boolean).join(' · ')||'Замовлення':'Замовлення'} close={close}>{!o?<div className="desk-spinner"/>:<><span className="desk-eyebrow">CHD-{o.id}</span><h2>{o.first_name||o.username||'Client'}</h2><p className="desk-muted">{o.phone_number||'—'} · @{o.username||'—'}</p>{o.responsible_name&&<p className="order-responsible-chip">👤 Відповідальний: <b>{o.responsible_name}</b></p>}
 <div className="desk-order-car"><Car/><div><b>{[o.brand,o.model,o.modification].filter(Boolean).join(' ')||o.car_name||'Авто'}</b><span>{o.plate||'—'} · {o.body_type||'—'}{o.has_ceramic?' · Ceramic':''}</span></div></div>
 <Tabs value={tab} onChange={setTab} items={[["overview","Огляд"],["services","Послуги"],["checklist","Чек-лист"],["photos","Фото"],["payment","Оплата"]]}/>{statusMeta[o.status]?.next&&<button className="desk-primary wide" onClick={async()=>{await post('/api/desktop/orders/'+id,{status:statusMeta[o.status].next},'PATCH');await load();changed()}}>{statusLabel(statusMeta[o.status].next!)} →</button>}
 <div hidden={tab!=='overview'}><div className="desk-form-grid"><label>Статус<select value={form.status||''} onChange={e=>setForm({...form,status:e.target.value})}>{['REQUESTED','PENDING_CONFIRMATION','CONFIRMED','CAR_ACCEPTED','IN_PROGRESS','INSPECTION','READY','COMPLETED','CANCELLED'].map(x=><option value={x} key={x}>{statusLabel(x)}</option>)}</select></label><label hidden={tab!=='payment'}>Оплата<select value={form.paymentStatus||''} onChange={e=>setForm({...form,paymentStatus:e.target.value})}>{['PENDING','UNPAID','PAID','REFUNDED'].map(x=><option value={x} key={x}>{statusLabel(x)}</option>)}</select></label><label>Відповідальний<select value={form.responsibleStaffId||''} onChange={e=>setForm({...form,responsibleStaffId:e.target.value?Number(e.target.value):null})}><option value="">Не призначено</option>{staffRows.filter(x=>x.status==='ACTIVE').map(x=><option key={x.id} value={x.id}>{x.staff_display_name||x.first_name||x.username||('Staff #'+x.id)} · {x.role}</option>)}</select></label><label>Початок роботи<input type="datetime-local" value={String(form.scheduledFor||'').slice(0,16)} onChange={e=>setForm({...form,scheduledFor:e.target.value})}/></label><label className="order-duration-field">Час виконання<input type="number" min="5" max="10080" step="5" disabled={!canDeadline} value={form.estimatedDurationMin||60} onChange={e=>setForm({...form,estimatedDurationMin:Number(e.target.value)})}/><small>{durationLabel(Number(form.estimatedDurationMin||60))}{o.duration_overridden?' · вручну':' · з послуг'}</small></label><label hidden={tab!=='payment'}>Кінцева сума<input type="number" value={form.finalPrice||0} onChange={e=>setForm({...form,finalPrice:Number(e.target.value)})}/></label></div>
 <div className={'order-deadline-panel '+(deadlinePreview&&Date.parse(deadlinePreview)<Date.now()&&!['COMPLETED','CANCELLED','REJECTED'].includes(String(form.status||''))?'overdue':'')}><div><span>Дедлайн</span><strong>{deadlinePreview?dt(deadlinePreview):'Не визначено'}</strong><small>{form.scheduledFor?'Початок '+String(form.scheduledFor).replace('T',' · '):'Спочатку вкажіть час початку'}</small></div>{canDeadline&&o.duration_overridden?<button onClick={async()=>{setSaving(true);try{await post('/api/desktop/orders/'+id,{resetDuration:true},'PATCH');await load();changed()}finally{setSaving(false)}}}>Авто з послуг</button>:null}</div>
 <label className="desk-field">Внутрішня примітка<textarea value={form.staffNote||''} onChange={e=>setForm({...form,staffNote:e.target.value})}/></label>
 <div className="desk-accelerated"><label><input type="checkbox" checked={!!form.accelerated} onChange={e=>setForm({...form,accelerated:e.target.checked,finalPrice:Number(form.finalPrice||0)+(e.target.checked?1:-1)*Number(form.acceleratedSurcharge||0)})}/><span>⚡ Прискорена робота</span></label><input type="number" value={form.acceleratedSurcharge||0} onChange={e=>setForm({...form,acceleratedSurcharge:Number(e.target.value),finalPrice:Number(form.finalPrice||0)+(form.accelerated?Number(e.target.value)-Number(form.acceleratedSurcharge||0):0)})} placeholder="+ PLN"/></div>
 </div><div hidden={tab!=='services'}><Panel title="Послуги замовлення" action={<span className="order-service-count">{(form.services||[]).length+(form.options||[]).length+(o.extras||[]).length}</span>}><div className="order-service-editor"><div className="order-service-columns"><div><b>Основні</b>{(catalog.services||[]).map((x:any)=><label key={x.id} className={(form.services||[]).includes(x.slug)?'selected':''}><input type="checkbox" checked={(form.services||[]).includes(x.slug)} onChange={()=>toggleBase('services',x.slug)}/><span>{x.title}</span><small>{money(x.price,x.currency)}</small></label>)}</div><div><b>Опції</b>{(catalog.options||[]).map((x:any)=><label key={x.id} className={(form.options||[]).includes(x.slug)?'selected':''}><input type="checkbox" checked={(form.options||[]).includes(x.slug)} onChange={()=>toggleBase('options',x.slug)}/><span>{x.title}</span><small>{money(x.price,x.currency)}</small></label>)}</div></div>
 <div className="order-add-service"><select value={pickType} onChange={e=>{setPickType(e.target.value as any);setPickId('')}}><option value="service">Послуга</option><option value="option">Додаткова опція</option></select><select value={pickId} onChange={e=>setPickId(e.target.value)}><option value="">Оберіть…</option>{(pickType==='service'?catalog.services:catalog.options).map((x:any)=><option key={x.id} value={x.id}>{x.title} · {money(x.price,x.currency)}</option>)}</select><button onClick={addCatalog} disabled={!pickId||serviceBusy}><Plus/>Додати до чеку</button></div>
 {(o.extras||[]).length>0&&<div className="order-extra-list"><b>Додані вручну</b>{(o.extras||[]).map((x:any)=><div key={x.id}><span>+ {x.title_snapshot||x.service_slug}</span><strong>{money(x.price_snapshot,x.currency)}</strong><button onClick={()=>removeExtra(x.id)} disabled={serviceBusy}><Trash2/></button></div>)}</div>}</div></Panel>
 <p className="order-service-note">Клієнту показується лише оновлений склад/статус замовлення. Канал, з якого Staff зробив зміну, у клієнтських повідомленнях не вказується.</p>
 </div>
 <div hidden={tab!=='checklist'}><Panel title="Операційний чек-лист"><div className="order-checklist">
  <div className={o.phone_number?'done':'attention'}>{o.phone_number?<Check/>:<AlertTriangle/>}<span><b>Контакт клієнта</b><small>{o.phone_number||'Телефон не вказано'}</small></span></div>
  <div className={form.responsibleStaffId?'done':'attention'}>{form.responsibleStaffId?<Check/>:<AlertTriangle/>}<span><b>Відповідальний</b><small>{o.responsible_name||'Потрібно призначити'}</small></span></div>
  <div className={form.scheduledFor?'done':'attention'}>{form.scheduledFor?<Check/>:<AlertTriangle/>}<span><b>Початок і дедлайн</b><small>{deadlinePreview?dt(deadlinePreview):'Час ще не визначено'}</small></span></div>
  <div className={(form.services||[]).length?'done':'attention'}>{(form.services||[]).length?<Check/>:<AlertTriangle/>}<span><b>Склад робіт</b><small>{(form.services||[]).length} основних · {(form.options||[]).length} додаткових</small></span></div>
  <div className={form.paymentStatus==='PAID'?'done':'attention'}>{form.paymentStatus==='PAID'?<Check/>:<AlertTriangle/>}<span><b>Оплата</b><small>{form.paymentStatus==='PAID'?'Оплачено':'Ще не оплачено'}</small></span></div>
 </div></Panel></div>
 <div hidden={tab!=='photos'}><Panel title="Фото замовлення"><div className="order-photos-empty"><ImageIcon/><b>Фотоматеріали замовлення</b><p>Цей розділ тепер відкривається окремо. Фото, прив’язані до замовлення, будуть показуватись тут; службові фото з інших розділів не змішуються.</p></div></Panel></div>
 <div hidden={tab!=='payment'}><div className="desk-form-grid"><label>Оплата<select value={form.paymentStatus||'UNPAID'} onChange={e=>setForm({...form,paymentStatus:e.target.value})}>{['PENDING','UNPAID','PAID','REFUNDED'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>Кінцева сума<input type="number" min="0" value={form.finalPrice??0} onChange={e=>setForm({...form,finalPrice:Number(e.target.value)})}/></label></div><div className="desk-money"><p><span>Розрахунок</span><b>{money(o.calculated_price,o.currency)}</b></p><p><span>Кінцева</span><strong>{money(form.finalPrice,o.currency)}</strong></p></div>
 </div><button className="desk-primary wide" onClick={save} disabled={saving}><Save/>{saving?'Збереження…':'Зберегти зміни'}</button></>}</Drawer>
}

