import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {
 Home,ClipboardList,Search,Car,Users,CalendarDays,Wrench,CreditCard,Megaphone,
 BarChart3,FileText,BadgeCheck,Settings,History,LayoutDashboard,LogOut,RefreshCw,
 ChevronRight,Lock,Unlock,Save,Upload,Download,RotateCcw,Send,Pause,Play,Eye,EyeOff,
 Monitor,Tablet,X,Check,AlertTriangle,Sun,Moon,ChevronDown,Globe2,Plus,Trash2,Pencil,Image as ImageIcon,Link2
} from 'lucide-react';
import {desktopLocales,desktopLocaleLabels,desktopLocaleNames,desktopT,normalizeDesktopLocale,type DesktopLocale} from '../../../desktopLocales';
import {api,post} from '../../api/desktopApi';
import {money,dt} from '../../format';
import type {Role,Bootstrap,Page} from '../../types/desktop';
import {Tabs} from '../../components/primitives';
import {showError} from '../../components/Toast';
import {Panel} from '../../components/Panel';
function ServiceEditorPortal({children}:{children:React.ReactNode}){return typeof document==='undefined'?<>{children}</>:createPortal(children,document.body)}
export function ServicesCatalog({locale,role}:{locale:DesktopLocale;role:Role}){
 const [editorTab,setEditorTab]=useState('main'),[translationLocale,setTranslationLocale]=useState<DesktopLocale>(locale);
 const t=(key:string)=>desktopT(locale,key),canEdit=role==='OWNER'||role==='ADMIN';
 const [data,setData]=useState<{services:any[];options:any[];total:number}>({services:[],options:[],total:0}),[q,setQ]=useState(''),[edit,setEdit]=useState<any>(null),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 const load=()=>api('/api/desktop/services').then(d=>setData({services:d.services||[],options:d.options||[],total:Number(d.total||0)})).catch(showError);
 useEffect(()=>{load()},[]);
 const emptyTranslations=()=>Object.fromEntries(['uk','pl','en','de','fr'].map(x=>[x,{title:'',description:''}]));
 const toTranslations=(rows:any[])=>{const out:any=emptyTranslations();for(const x of rows||[])out[x.locale]={title:x.title||'',description:x.description||''};return out};
 const openService=async(x:any)=>{if(!canEdit)return;setEditorTab('main');const d=await api('/api/desktop/services/detail/'+x.id);setEdit({kind:'service',mode:'edit',id:x.id,slug:x.slug,price:Number(d.service.base_price||0),currency:d.service.base_currency||'PLN',enabled:!!d.service.enabled,archived:!!d.service.archived,durationMin:Number(d.service.duration_min||0),category:d.service.category||'DETAILING',imageUrl:d.service.image_url||'',iconKey:d.service.icon_key||'',isPopular:!!d.service.is_popular,sortOrder:Number(d.service.sort_order||0),translations:toTranslations(d.translations),requirements:{requireCondition:Number(d.requirements?.require_condition??1)!==0,requireVehicle:Number(d.requirements?.require_vehicle??1)!==0,allowOptions:Number(d.requirements?.allow_options??1)!==0,allowMultipleOptions:Number(d.requirements?.allow_multiple_options??1)!==0},optionIds:d.optionIds||[],vip:Object.fromEntries(['VIP','VIP_PLUS'].map(tier=>{const r=(d.vip||[]).find((z:any)=>z.tier===tier);return [tier,r?{mode:r.mode||'PERCENT',value:r.mode==='PRICE'?Number(r.fixed_price||0):r.mode==='MULTIPLIER'?Number(r.multiplier||1):Number(r.percent_discount||0),currency:r.currency||d.service.base_currency||'PLN'}:{mode:'PERCENT',value:'',currency:d.service.base_currency||'PLN'}]}))})};
 const openOption=async(x:any)=>{if(!canEdit)return;setEditorTab('main');const d=await api('/api/desktop/service-options/detail/'+x.id);setEdit({kind:'option',mode:'edit',id:x.id,slug:x.slug,price:Number(d.option.price||0),currency:d.option.base_currency||'PLN',enabled:!!d.option.enabled,pricingType:d.option.pricing_type||'FIXED',iconKey:d.option.icon_key||'',sortOrder:Number(d.option.sort_order||0),translations:toTranslations(d.translations),serviceIds:d.serviceIds||[],vip:Object.fromEntries(['VIP','VIP_PLUS'].map(tier=>{const r=(d.vip||[]).find((z:any)=>z.tier===tier);return [tier,r?{mode:r.mode||'PERCENT',value:r.mode==='PRICE'?Number(r.fixed_price||0):r.mode==='MULTIPLIER'?Number(r.multiplier||1):Number(r.percent_discount||0),currency:r.currency||d.option.base_currency||'PLN'}:{mode:'PERCENT',value:'',currency:d.option.base_currency||'PLN'}]}))})};
 const newService=()=>{setEditorTab('main');setEdit({kind:'service',mode:'new',slug:'',price:0,currency:'PLN',enabled:true,archived:false,durationMin:60,category:'DETAILING',imageUrl:'',iconKey:'',isPopular:false,sortOrder:0,translations:emptyTranslations(),requirements:{requireCondition:true,requireVehicle:true,allowOptions:true,allowMultipleOptions:true},optionIds:[],vip:{VIP:{mode:'PERCENT',value:'',currency:'PLN'},VIP_PLUS:{mode:'PERCENT',value:'',currency:'PLN'}}})};
 const newOption=()=>{setEditorTab('main');setEdit({kind:'option',mode:'new',slug:'',price:0,currency:'PLN',enabled:true,pricingType:'FIXED',iconKey:'',sortOrder:0,translations:emptyTranslations(),serviceIds:[],vip:{VIP:{mode:'PERCENT',value:'',currency:'PLN'},VIP_PLUS:{mode:'PERCENT',value:'',currency:'PLN'}}})};
 useEffect(()=>{const entity=location.hash.split('/')[1];if(entity==='new'&&canEdit)newService();else if(entity&&data.services.length){const found=data.services.find(x=>x.slug===decodeURIComponent(entity));if(found)openService(found)}},[data.services.length,location.hash]);
 const setTr=(loc:string,key:'title'|'description',value:string)=>setEdit({...edit,translations:{...edit.translations,[loc]:{...edit.translations[loc],[key]:value}}});
 const toggleId=(key:'optionIds'|'serviceIds',id:number)=>{const a=[...(edit[key]||[])];setEdit({...edit,[key]:a.includes(id)?a.filter((x:number)=>x!==id):[...a,id]})};
 const save=async()=>{if(!edit)return;setSaving(true);setMsg('');try{if(edit.kind==='service'){const payload={slug:edit.slug,price:Number(edit.price||0),currency:edit.currency,enabled:!!edit.enabled,archived:!!edit.archived,durationMin:Number(edit.durationMin||0),category:edit.category,imageUrl:edit.imageUrl,iconKey:edit.iconKey,isPopular:!!edit.isPopular,sortOrder:Number(edit.sortOrder||0),translations:edit.translations,requirements:edit.requirements,optionIds:edit.optionIds};if(edit.mode==='new')await post('/api/desktop/services',payload);else await post('/api/desktop/services/'+edit.id,payload,'PATCH')}else{const payload={slug:edit.slug,price:Number(edit.price||0),currency:edit.currency,enabled:!!edit.enabled,pricingType:edit.pricingType,iconKey:edit.iconKey,sortOrder:Number(edit.sortOrder||0),translations:edit.translations,serviceIds:edit.serviceIds};if(edit.mode==='new')await post('/api/desktop/service-options',payload);else await post('/api/desktop/service-options/'+edit.id,payload,'PATCH')}setMsg('✅ Зміни збережено');setEdit(null);await load()}catch(e:any){setMsg('⚠️ '+String(e?.message||e))}finally{setSaving(false)}};
 const remove=async()=>{if(!edit||edit.mode==='new')return;if(!confirm(edit.kind==='service'?'Архівувати цю послугу?':'Видалити цю додаткову опцію?'))return;setSaving(true);try{await api(edit.kind==='service'?'/api/desktop/services/'+edit.id:'/api/desktop/service-options/'+edit.id,{method:'DELETE'});setEdit(null);await load();setMsg(edit.kind==='service'?'Послугу архівовано':'Опцію видалено')}finally{setSaving(false)}};
 const vipPath=(tier:'VIP'|'VIP_PLUS')=>edit?.kind==='option'?'/api/desktop/service-options/'+edit.id+'/vip-pricing/'+tier:'/api/desktop/services/'+edit.id+'/vip-pricing/'+tier;
 const saveVipRule=async(tier:'VIP'|'VIP_PLUS')=>{const r=edit?.vip?.[tier];if(!edit?.id||!r||r.value==='')return;await post(vipPath(tier),{mode:r.mode,value:Number(r.value),currency:r.currency},'PUT');setMsg('✅ '+tier+' ціна збережена')};
 const clearVipRule=async(tier:'VIP'|'VIP_PLUS')=>{if(!edit?.id)return;await api(vipPath(tier),{method:'DELETE'});setEdit({...edit,vip:{...edit.vip,[tier]:{mode:'PERCENT',value:'',currency:edit.currency}}});setMsg('VIP-правило скинуто до стандартної знижки')};
 const term=q.trim().toLowerCase(),main=data.services.filter(x=>!term||String(x.title+' '+x.slug+' '+x.category).toLowerCase().includes(term)),extras=data.options.filter(x=>!term||String(x.title+' '+x.slug+' '+x.service_slugs).toLowerCase().includes(term));
 return <><div className="desk-toolbar"><div className="desk-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('services.search')}/></div><button onClick={load}><RefreshCw/>{t('common.refresh')}</button>{canEdit&&<><button className="desk-primary" onClick={newService}><Plus/>Послуга</button><button onClick={newOption}><Plus/>Опція</button></>}<span className="desk-catalog-count">{t('services.total')}: <b>{data.total}</b></span></div>
 <div className="service-catalog-summary"><div><Wrench/><span>{t('services.main')}</span><b>{data.services.length}</b></div><div><Check/><span>{t('services.options')}</span><b>{data.options.length}</b></div><p>{canEdit?'Повний Desktop CRUD: ціни, статуси, категорії, тексти 5 мов, зображення/Icon URL, правила калькулятора та зв’язки з додатковими опціями.':t('services.sync')}</p></div>
 {msg&&<div className="desk-banner">{msg}</div>}
 <Panel title={t('services.main')+' · '+main.length}><div className="desk-table-wrap"><table><thead><tr><th>{t('page.services')}</th><th>{t('services.category')}</th><th>{t('orders.price')}</th><th>{t('services.currency')}</th><th>{t('services.duration')}</th><th>{t('services.state')}</th></tr></thead><tbody>{main.map(x=><tr key={x.id} className={canEdit?'editable-row':''} onClick={()=>openService(x)}><td><div className="service-title-cell">{x.image_url?<img src={x.image_url} alt=""/>:<span className="service-icon-placeholder"><Wrench/></span>}<div><b>{x.title}</b></div></div></td><td>{x.category||'—'}</td><td><b>{Number(x.base_price||0).toFixed(2)}</b></td><td>{x.base_currency||'PLN'}</td><td>{x.duration_min||0} min</td><td><span className="desk-status">{x.archived?'Архівна':x.enabled?'Активна':'Вимкнена'}</span></td></tr>)}</tbody></table></div></Panel>
 <Panel title={t('services.options')+' · '+extras.length}><div className="desk-table-wrap"><table><thead><tr><th>{t('services.options')}</th><th>{t('services.for')}</th><th>{t('orders.price')}</th><th>{t('services.currency')}</th><th>{t('services.pricing')}</th><th>{t('services.state')}</th></tr></thead><tbody>{extras.map(x=><tr key={x.id} className={canEdit?'editable-row':''} onClick={()=>openOption(x)}><td><b>{x.title}</b><small>{x.slug}</small></td><td>{String(x.service_slugs||'').split(',').filter(Boolean).join(', ')||t('services.unbound')}</td><td><b>{Number(x.price||0).toFixed(2)}</b></td><td>{x.base_currency||'PLN'}</td><td>{x.pricing_type||'FIXED'}</td><td><span className="desk-status">{x.enabled?'Активна':'Вимкнена'}</span></td></tr>)}</tbody></table></div></Panel>
 {edit&&<ServiceEditorPortal><div className="desk-drawer-backdrop service-editor-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEdit(null)}><aside className="desk-drawer service-edit-drawer full-service-editor"><button className="desk-drawer-close" onClick={()=>setEdit(null)}><X/></button><span className="desk-eyebrow">{edit.mode==='new'?'NEW ':''}{edit.kind==='service'?'SERVICE':'ADD-ON'}</span><h2>{edit.mode==='new'?'Створення':edit.translations?.[locale]?.title||edit.slug}</h2>
 <Tabs value={editorTab} onChange={setEditorTab} items={[["main","Основне й ціна"],["options",edit.kind==='service'?"Опції та медіа":"Прив’язка"],...(edit.mode!=='new'?[["vip","VIP-ціни"] as [string,string]]:[]),["content","Контент"]]}/><div hidden={editorTab!=='main'} className="service-editor-section"><h3>Основне й ціна</h3><div className="desk-form-grid"><label>Код послуги<input disabled={edit.mode!=='new'} value={edit.slug} onChange={e=>setEdit({...edit,slug:e.target.value})}/></label><label>Ціна<input type="number" min="0" step="0.01" value={edit.price} onChange={e=>setEdit({...edit,price:e.target.value})}/></label><label>Валюта<select value={edit.currency} onChange={e=>setEdit({...edit,currency:e.target.value})}><option>PLN</option><option>UAH</option><option>USD</option></select></label><label>Порядок<input type="number" value={edit.sortOrder} onChange={e=>setEdit({...edit,sortOrder:e.target.value})}/></label>{edit.kind==='service'?<><label>Категорія<input value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}/></label><label>Тривалість, хв<input type="number" min="0" value={edit.durationMin} onChange={e=>setEdit({...edit,durationMin:e.target.value})}/></label></>:<label>Тип ціни<select value={edit.pricingType} onChange={e=>setEdit({...edit,pricingType:e.target.value})}><option>FIXED</option><option>PERCENT</option><option>MULTIPLIER</option></select></label>}<label className="service-enabled-toggle"><span>Активна</span><input type="checkbox" checked={!!edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/></label>{edit.kind==='service'&&<label className="service-enabled-toggle"><span>Популярна ⭐</span><input type="checkbox" checked={!!edit.isPopular} onChange={e=>setEdit({...edit,isPopular:e.target.checked})}/></label>}</div></div>
 {edit.kind==='service'?<div hidden={editorTab!=='options'} className="service-editor-section"><h3><ImageIcon/> Зображення та калькулятор</h3><label className="desk-field">Image URL<input value={edit.imageUrl||''} placeholder="https://…/service.webp" onChange={e=>setEdit({...edit,imageUrl:e.target.value})}/></label>{edit.imageUrl&&<div className="service-image-preview"><img src={edit.imageUrl} alt="preview"/></div>}<label className="desk-field">Icon key<input value={edit.iconKey||''} placeholder="exterior-detailing" onChange={e=>setEdit({...edit,iconKey:e.target.value})}/></label><div className="service-rule-grid">{[['requireCondition','Питати стан авто'],['requireVehicle','Питати тип авто'],['allowOptions','Дозволити опції'],['allowMultipleOptions','Кілька опцій']].map(([key,label])=><label key={key}><input type="checkbox" checked={!!edit.requirements[key]} onChange={e=>setEdit({...edit,requirements:{...edit.requirements,[key]:e.target.checked}})}/><span>{label}</span></label>)}</div><h4>Доступні додаткові опції</h4><div className="service-link-grid">{data.options.map(x=><label key={x.id} className={(edit.optionIds||[]).includes(x.id)?'selected':''}><input type="checkbox" checked={(edit.optionIds||[]).includes(x.id)} onChange={()=>toggleId('optionIds',x.id)}/><span>{x.title}</span></label>)}</div></div>:<div hidden={editorTab!=='options'} className="service-editor-section"><h3><Link2/> Прив’язка до послуг</h3><label className="desk-field">Icon key<input value={edit.iconKey||''} onChange={e=>setEdit({...edit,iconKey:e.target.value})}/></label><div className="service-link-grid">{data.services.map(x=><label key={x.id} className={(edit.serviceIds||[]).includes(x.id)?'selected':''}><input type="checkbox" checked={(edit.serviceIds||[]).includes(x.id)} onChange={()=>toggleId('serviceIds',x.id)}/><span>{x.title}</span></label>)}</div></div>}
 {edit.mode!=='new'&&<div hidden={editorTab!=='vip'} className="service-editor-section vip-editor-section"><h3>💎 VIP ціноутворення · {edit.kind==='service'?'послуга':'додаткова опція'}</h3><p className="desk-muted vip-editor-note">Окреме правило для VIP і VIP+. Якщо правило не задане, використовується стандартна знижка рівня.</p><div className="vip-price-grid">{(['VIP','VIP_PLUS'] as const).map(tier=>{const r=edit.vip?.[tier]||{mode:'PERCENT',value:'',currency:edit.currency};return <div key={tier}><b>{tier}</b><select value={r.mode} onChange={e=>setEdit({...edit,vip:{...edit.vip,[tier]:{...r,mode:e.target.value}}})}><option value="PERCENT">% знижки</option><option value="PRICE">Фіксована ціна</option><option value="MULTIPLIER">Multiplier</option></select><input type="number" step=".01" value={r.value} placeholder={r.mode==='PERCENT'?'10':r.mode==='PRICE'?'220':'0.90'} onChange={e=>setEdit({...edit,vip:{...edit.vip,[tier]:{...r,value:e.target.value}}})}/>{r.mode==='PRICE'&&<select value={r.currency} onChange={e=>setEdit({...edit,vip:{...edit.vip,[tier]:{...r,currency:e.target.value}}})}><option>PLN</option><option>UAH</option><option>USD</option></select>}<button onClick={()=>saveVipRule(tier)}>Save</button><button className="danger-mini" onClick={()=>clearVipRule(tier)}>Reset</button></div>})}</div></div>}
 <div hidden={editorTab!=='content'} className="service-editor-section"><h3>Контент</h3><Tabs value={translationLocale} onChange={x=>setTranslationLocale(x as DesktopLocale)} items={desktopLocales.map(x=>[x,desktopLocaleLabels[x]+(edit.translations?.[x]?.title?' ✓':' !')])}/><div className="service-translations">{[translationLocale].map(loc=><div key={loc}><div className="translation-head"><b>{desktopLocaleLabels[loc]} · {desktopLocaleNames[loc]}</b></div><input placeholder="Назва" value={edit.translations?.[loc]?.title||''} onChange={e=>setTr(loc,'title',e.target.value)}/><textarea placeholder="Опис" value={edit.translations?.[loc]?.description||''} onChange={e=>setTr(loc,'description',e.target.value)}/></div>)}</div></div>
 <div className="service-editor-actions">{edit.mode!=='new'&&<button className="danger" onClick={remove} disabled={saving}><Trash2/>{edit.kind==='service'?'Архівувати':'Видалити'}</button>}<button className="desk-primary" disabled={saving||!edit.slug.trim()} onClick={save}><Save/>{saving?'Збереження…':'Зберегти'}</button></div></aside></div></ServiceEditorPortal>}</>
}

