export const carModelCatalog:Record<string,string[]>={
 'BMW':['1 Series','2 Series','3 Series','4 Series','5 Series','6 Series','7 Series','8 Series','X1','X2','X3','X4','X5','X6','X7','XM','Z4','i3','i4','i5','i7','iX','M2','M3','M4','M5','M8'],
 'Mercedes-Benz':['A-Class','B-Class','C-Class','CLA','CLE','CLS','E-Class','S-Class','GLA','GLB','GLC','GLE','GLS','G-Class','AMG GT','SL','EQA','EQB','EQE','EQS','V-Class','Citan','Sprinter'],
 'Audi':['A1','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4 e-tron','Q5','Q6 e-tron','Q7','Q8','TT','R8','e-tron GT','RS 3','RS 4','RS 5','RS 6','RS 7','RS Q3','RS Q8'],
 'Volkswagen':['Polo','Golf','Golf Variant','Passat','Arteon','T-Cross','T-Roc','Tiguan','Touareg','Touran','Caddy','Multivan','Transporter','ID.3','ID.4','ID.5','ID.7','ID.Buzz'],
 'Porsche':['718 Boxster','718 Cayman','911','Panamera','Macan','Cayenne','Taycan'],
 'Tesla':['Model 3','Model S','Model X','Model Y','Cybertruck'],
 'Toyota':['Aygo X','Yaris','Yaris Cross','Corolla','Corolla Touring Sports','Camry','Prius','C-HR','RAV4','Highlander','Land Cruiser','Hilux','Proace','GR Yaris','GR86','Supra','bZ4X'],
 'Lexus':['LBX','UX','NX','RX','RZ','ES','LS','LC','LM','GX'],
 'Ford':['Fiesta','Focus','Mondeo','Puma','Kuga','Explorer','Mustang','Mustang Mach-E','Ranger','Tourneo Connect','Tourneo Custom','Transit Connect','Transit Custom','Transit'],
 'Volvo':['EX30','EX40','EC40','EX90','XC40','XC60','XC90','S60','S90','V60','V90'],
 'Skoda':['Fabia','Scala','Octavia','Superb','Kamiq','Karoq','Kodiaq','Enyaq','Elroq'],
 'Kia':['Picanto','Rio','Ceed','ProCeed','XCeed','Stonic','Niro','Sportage','Sorento','EV3','EV6','EV9'],
 'Hyundai':['i10','i20','i30','Bayon','Kona','Tucson','Santa Fe','Ioniq 5','Ioniq 6'],
 'Honda':['Jazz','Civic','HR-V','ZR-V','CR-V','e:Ny1'],
 'Mazda':['Mazda2','Mazda3','Mazda6','CX-30','CX-5','CX-60','CX-80','MX-5','MX-30'],
 'Nissan':['Micra','Juke','Qashqai','X-Trail','Ariya','Leaf','Townstar','Primastar','Interstar','GT-R'],
 'Land Rover':['Defender','Discovery','Discovery Sport'],
 'Range Rover':['Range Rover','Range Rover Sport','Velar','Evoque'],
 'Jaguar':['XE','XF','F-Type','E-Pace','F-Pace','I-Pace'],
 'Peugeot':['208','308','408','508','2008','3008','5008','Rifter','Partner','Traveller','Expert','e-208','e-3008'],
 'Renault':['Clio','Captur','Megane','Austral','Espace','Rafale','Arkana','Scenic E-Tech','Megane E-Tech','Kangoo','Trafic','Master'],
 'Citroen':['C3','C3 Aircross','C4','C4 X','C5 Aircross','Berlingo','SpaceTourer','Jumpy','Jumper'],
 'Fiat':['500','500e','600','Panda','Tipo','Doblo','Scudo','Ducato'],
 'Jeep':['Avenger','Renegade','Compass','Wrangler','Grand Cherokee'],
 'Mini':['Cooper 3-Door','Cooper 5-Door','Cooper Convertible','Countryman','Aceman','Clubman'],
 'Opel':['Corsa','Astra','Mokka','Crossland','Grandland','Combo','Zafira','Vivaro','Movano'],
 'Seat':['Ibiza','Leon','Leon Sportstourer','Arona','Ateca','Tarraco'],
 'Cupra':['Born','Leon','Leon Sportstourer','Formentor','Ateca','Tavascan','Terramar'],
 'Mitsubishi':['Colt','ASX','Eclipse Cross','Outlander','L200'],
 'Subaru':['Impreza','Crosstrek','Forester','Outback','Solterra','BRZ'],
 'Bentley':['Bentayga','Continental GT','Continental GTC','Flying Spur'],
 'Rolls-Royce':['Cullinan','Ghost','Phantom','Spectre','Wraith','Dawn'],
 'Lamborghini':['Urus','Revuelto','Huracan','Aventador'],
 'Ferrari':['Roma','Purosangue','296 GTB','296 GTS','SF90 Stradale','SF90 Spider','812 Superfast','F8 Tributo'],
 'Maserati':['Grecale','Levante','Ghibli','Quattroporte','GranTurismo','GranCabrio','MC20'],
 'Aston Martin':['DB12','DBX','Vantage','Vanquish'],
 'McLaren':['Artura','GT','750S','720S','570S'],
 'Genesis':['G70','G80','G90','GV60','GV70','GV80'],
 'DS':['DS 3','DS 4','DS 7','DS 9'],
 'Smart':['#1','#3','Fortwo','Forfour'],
 'Abarth':['500e','595','695'],
 'Infiniti':['Q30','Q50','Q60','QX30','QX50','QX60','QX80'],
 'Acura':['Integra','TLX','RDX','MDX','ZDX'],
 'Cadillac':['CT4','CT5','XT4','XT5','XT6','Escalade','Lyriq'],
 'Chevrolet':['Camaro','Corvette','Malibu','Trax','Trailblazer','Equinox','Traverse','Tahoe','Suburban','Silverado'],
 'Dodge':['Charger','Challenger','Durango','Hornet'],
 'RAM':['1500','2500','3500'],
 'GMC':['Terrain','Acadia','Yukon','Sierra','Hummer EV'],
 'Chrysler':['300','Pacifica'],
 'Alfa Romeo':['Giulia','Stelvio','Tonale','Junior'],
 'Dacia':['Sandero','Sandero Stepway','Jogger','Duster','Bigster','Spring'],
 'Suzuki':['Swift','Vitara','S-Cross','Jimny','Across','Swace'],
 'MG':['MG3','MG4','MG5','ZS','HS','Marvel R','Cyberster'],
 'Polestar':['Polestar 2','Polestar 3','Polestar 4'],
 'BYD':['Dolphin','Atto 3','Seal','Seal U','Tang'],
 'Geely':['Coolray','Atlas','Monjaro','Emgrand'],
 'Chery':['Tiggo 4','Tiggo 7','Tiggo 8','Arrizo 8'],
};
export const carBrands=Object.keys(carModelCatalog).sort((a,b)=>a.localeCompare(b));
export const modelsForBrand=(brand:string)=>carModelCatalog[brand]||[];
export const modelAssetKey=(brand?:string,model?:string)=>[brand,model].filter(Boolean).join('-').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
