import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {statusLabel,statusMeta} from '../config/statusMeta';
import {money} from '../format';
export function StatusBadge({status}:{status:string}){return <span className={'desk-status tone-'+(statusMeta[status]?.tone||'neutral')}>{statusLabel(status)}</span>}
export function Money({value,currency='PLN'}:{value:number;currency?:string}){return <span>{money(value,currency)}</span>}
export function Skeleton(){return <div className="skeleton" role="status" aria-label="Завантаження">{[1,2,3,4].map(x=><div key={x}/>)}</div>}
export function EmptyState({children,action}:{children:ReactNode;action?:ReactNode}){return <div className="desk-empty"><p>{children}</p>{action}</div>}
export function Tabs({items,value,onChange}:{items:[string,string][];value:string;onChange:(v:string)=>void}){return <div className="desk-segment" role="tablist">{items.map(([id,label])=><button key={id} role="tab" aria-selected={id===value} className={id===value?'active':''} onClick={()=>onChange(id)}>{label}</button>)}</div>}
export function Drawer({title,close,children,modal=false}:{title:string;close:()=>void;children:ReactNode;modal?:boolean}){const ref=useRef<HTMLDivElement>(null),id=useId();useEffect(()=>{const previous=document.activeElement as HTMLElement;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const list=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href],[tabindex="0"]')||[]).filter(x=>x.offsetParent!==null);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};ref.current?.focus();document.addEventListener('keydown',onKey);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=overflow;previous?.focus()}},[close]);const node=<div className={'desk-drawer-backdrop '+(modal?'modal-backdrop':'')} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className={modal?'desk-modal':'desk-drawer'} role="dialog" aria-modal="true" aria-labelledby={id} ref={ref} tabIndex={-1}><div className="desk-drawer-header"><h2 id={id}>{title}</h2><button className="desk-drawer-close" aria-label="Закрити" onClick={close}>×</button></div><div className="desk-drawer-content">{children}</div></div></div>;return typeof document==='undefined'?node:createPortal(node,document.body)}
export const Modal=(props:Parameters<typeof Drawer>[0])=><Drawer {...props} modal/>;
export function DataTable<T extends {id:number}>({rows,columns,onRow}:{rows:T[];columns:{key:string;label:string;render:(row:T)=>ReactNode;sort?:(row:T)=>string|number}[];onRow?:(row:T)=>void}){const [sort,setSort]=useState(''),[direction,setDirection]=useState(1),[page,setPage]=useState(0);const col=columns.find(c=>c.key===sort),sorted=col?.sort?[...rows].sort((a,b)=>String(col.sort!(a)).localeCompare(String(col.sort!(b)),undefined,{numeric:true})*direction):rows;const pages=Math.max(1,Math.ceil(rows.length/25)),safePage=Math.min(page,pages-1);return <><div className="desk-table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key} aria-sort={sort===c.key?(direction===1?'ascending':'descending'):undefined}><button disabled={!c.sort} onClick={()=>{setSort(c.key);setDirection(sort===c.key?-direction:1)}}>{c.label}{sort===c.key?(direction===1?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{sorted.slice(safePage*25,safePage*25+25).map(row=><tr key={row.id} tabIndex={onRow?0:undefined} onClick={()=>onRow?.(row)} onKeyDown={e=>{if(e.key==='Enter')onRow?.(row)}}>{columns.map(c=><td key={c.key}>{c.render(row)}</td>)}</tr>)}</tbody></table>{!rows.length&&<EmptyState>За цими умовами нічого не знайдено.</EmptyState>}</div><div className="table-pagination"><button disabled={safePage===0} onClick={()=>setPage(safePage-1)}>←</button><span>{safePage+1} / {pages} · {rows.length}</span><button disabled={safePage+1>=pages} onClick={()=>setPage(safePage+1)}>→</button></div></>}
