import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Home,Sparkles,Calculator,Crown,UserRound,ChevronRight,Car,ShieldCheck,Droplets,Gem,Gift,Globe2,Check,ArrowLeft,Loader2,MessageCircle,Clock3,X,TriangleAlert,ClipboardList,RefreshCw,Trash2} from 'lucide-react';
import {api,Service,ServiceOption,Session} from './lib/api';
import {haptic,initTelegram,notify,openBot,shareTelegramLink,telegramLanguage} from './lib/telegram';
import {createTranslator,Locale,localeLabels,localeNames,normalizeLocale,splashSlogan,TranslationKey} from './locales';
import {motion} from './config/motion';

type Tab='home'|'services'|'calculator'|'vip'|'profile'|'orders';
const vehicles=[['sedan','vehicle.sedan','/vehicle-types/sedan.webp'],['hatchback','vehicle.hatchback','/vehicle-types/hatchback.webp'],['suv','vehicle.suv','/vehicle-types/suv.webp'],['large-suv','vehicle.largeSuv','/vehicle-types/large-suv.webp'],['van','vehicle.van','/vehicle-types/van.webp']] as const;
const conditions=[['light','condition.light'],['normal','condition.normal'],['dirty','condition.dirty'],['very-dirty','condition.veryDirty']] as const;
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const friendlyError=(e:unknown,t:(key:TranslationKey)=>string)=>{const m=e instanceof Error?e.message:String(e||'');if(/BOT_TOKEN/i.test(m))return t('errors.botToken');if(/Invalid or expired Telegram session/i.test(m))return t('errors.telegramSession');if(/maintenance/i.test(m))return t('errors.maintenance');if(/Access limited/i.test(m))return t('errors.accessLimited');if(/outside working hours/i.test(m))return t('errors.outsideHours');if(/Emergency mode/i.test(m))return t('errors.emergencyUnavailable');if(/60 minutes/i.test(m))return t('errors.rateLimit');return t('errors.generic')};
type SeasonalTheme='DEFAULT'|'HALLOWEEN'|'NEW_YEAR'|'EASTER'|undefined;
const seasonalDecorPlacements=[
 {left:'4%',top:'14%',size:22,dur:17,delay:-2,alpha:.18},{left:'82%',top:'16%',size:24,dur:18,delay:-6,alpha:.16},
 {left:'12%',top:'26%',size:28,dur:22,delay:-8,alpha:.18},{left:'70%',top:'28%',size:20,dur:16,delay:-4,alpha:.15},
 {left:'88%',top:'33%',size:30,dur:19,delay:-10,alpha:.17},{left:'7%',top:'42%',size:24,dur:18,delay:-1,alpha:.14},
 {left:'58%',top:'41%',size:22,dur:20,delay:-12,alpha:.15},{left:'25%',top:'50%',size:34,dur:24,delay:-9,alpha:.16},
 {left:'78%',top:'54%',size:26,dur:18,delay:-3,alpha:.14},{left:'9%',top:'62%',size:24,dur:21,delay:-11,alpha:.13},
 {left:'50%',top:'62%',size:20,dur:16,delay:-5,alpha:.12},{left:'86%',top:'68%',size:28,dur:22,delay:-14,alpha:.16},
 {left:'18%',top:'74%',size:30,dur:20,delay:-13,alpha:.14},{left:'64%',top:'77%',size:22,dur:17,delay:-7,alpha:.13},
 {left:'40%',top:'84%',size:26,dur:23,delay:-15,alpha:.12},{left:'90%',top:'86%',size:24,dur:19,delay:-9,alpha:.14}
] as const;
const seasonalDecorIcons:Record<Exclude<SeasonalTheme,undefined>,string[]>={
 DEFAULT:[],
 HALLOWEEN:['🎃','💀','🕯️','⚰️','🪦','🦇','🍬','🕸️'],
 NEW_YEAR:['❄️','🎄','✨','🎁','🌟','☃️','🧣','🔔'],
 EASTER:['🥚','🐣','🐇','🌸','🪻','🧺','✨','🌼']
};
const applyTheme=(theme?:Session['theme'])=>{
 const root=document.documentElement;
 root.style.setProperty('--h1',theme?.fontH1||'clamp(1.7rem,7vw,2.35rem)');
 root.style.setProperty('--h2',theme?.fontH2||'clamp(1.25rem,5.4vw,1.6rem)');
 root.style.setProperty('--body',theme?.fontBody||'clamp(.94rem,3.8vw,1rem)');
 root.style.setProperty('--small',theme?.fontSmall||'clamp(.78rem,3.2vw,.875rem)');
 const seasonal=(theme?.seasonalTheme||'DEFAULT').toUpperCase();
 const seasonalColors:Record<string,string>={HALLOWEEN:'#ff8a00',NEW_YEAR:'#4de8ff',EASTER:'#ff86d8'};
 const base=/^#[0-9a-f]{6}$/i.test(theme?.neonColor||'')?(theme?.neonColor as string):'#a4ff00';
 root.style.setProperty('--neon-color',seasonalColors[seasonal]||base);
 for(const cls of ['theme-halloween','theme-new-year','theme-easter'])root.classList.remove(cls);
 if(seasonal==='HALLOWEEN')root.classList.add('theme-halloween');
 if(seasonal==='NEW_YEAR')root.classList.add('theme-new-year');
 if(seasonal==='EASTER')root.classList.add('theme-easter');
 const rainbow=seasonal==='DEFAULT'&&theme?.neonMode==='RAINBOW';
 root.classList.toggle('theme-rainbow',rainbow);
 root.classList.toggle('theme-static',!rainbow);
};

export function App(){
 const initialTab=useMemo<Tab>(()=>{const v=new URLSearchParams(location.search).get('startapp');return v==='calculator'||v==='orders'?v:'home'},[]);
 const [session,setSession]=useState<Session|null>(null),[services,setServices]=useState<Service[]>([]),[serviceOptions,setServiceOptions]=useState<ServiceOption[]>([]),[content,setContent]=useState<Record<string,string>>({}),[tab,setTab]=useState<Tab>(initialTab);
 const initialLocale=useMemo(()=>normalizeLocale(localStorage.getItem('chameleon.locale')||telegramLanguage()||navigator.language),[]);
 const [locale,setLocaleState]=useState<Locale>(initialLocale),[currency,setCurrency]=useState('PLN');
 const [startup,setStartup]=useState({stage:'INIT',progress:15,error:''}),[splash,setSplash]=useState(true),[directWebBlocked,setDirectWebBlocked]=useState(false);
 const t=useMemo(()=>createTranslator(locale),[locale]);
 const setLocale=(next:Locale)=>{localStorage.setItem('chameleon.locale',next);setLocaleState(next)};

 useEffect(()=>{document.documentElement.lang=locale},[locale]);
 useEffect(()=>{applyTheme(session?.theme)},[session?.theme?.fontH1,session?.theme?.fontH2,session?.theme?.fontBody,session?.theme?.fontSmall,session?.theme?.neonMode,session?.theme?.neonColor,session?.theme?.seasonalMode,session?.theme?.seasonalTheme]);
 useEffect(()=>{initTelegram();(async()=>{const started=Date.now();try{
   setStartup({stage:'AUTH',progress:35,error:''});
   const s=await api.session();
   setStartup({stage:'PROFILE',progress:55,error:''});
   const saved=localStorage.getItem('chameleon.locale');
   const resolved=normalizeLocale(saved||s.user.locale||telegramLanguage());
   const resolvedCurrency=(s.user.currency||'PLN').toUpperCase();
   setLocale(resolved);setCurrency(resolvedCurrency);setSession(s);
   setStartup({stage:'CONFIG',progress:80,error:''});
   const [sv,opt,ct]=await Promise.all([api.services(resolved,resolvedCurrency),api.options(resolved,resolvedCurrency),api.content(resolved)]);
   setServices(sv.services);setServiceOptions(opt.options||[]);setContent(ct.content||{});
   setStartup({stage:'READY',progress:100,error:''});
   const elapsed=Date.now()-started;if(elapsed<motion.splashMin)await wait(motion.splashMin-elapsed);await wait(160);setSplash(false);
  }catch(e:unknown){const raw=e instanceof Error?e.message:String(e||'');if(raw==='DIRECT_WEB_DISABLED'){setDirectWebBlocked(true);setSplash(false);return}setStartup(x=>({...x,error:friendlyError(e,t)}));}})()},[]);
 useEffect(()=>{if(!session)return;Promise.all([api.services(locale,currency),api.options(locale,currency),api.content(locale)]).then(([x,opt,ct])=>{setServices(x.services);setServiceOptions(opt.options||[]);setContent(ct.content||{})}).catch(()=>{})},[locale,currency,session]);
 // Staff can change opening hours from Telegram while the Mini App is already open.
 // Refresh runtime business state automatically so the closed/open banner follows D1
 // without forcing the client to kill and reopen Telegram.
 useEffect(()=>{if(!session)return;let stopped=false;const refresh=()=>api.session().then(fresh=>{if(stopped)return;setSession(prev=>prev?{...prev,...fresh,user:{...prev.user,...fresh.user}}:fresh)}).catch(()=>{});const timer=setInterval(refresh,15000);const onVisibility=()=>{if(document.visibilityState==='visible')refresh()};document.addEventListener('visibilitychange',onVisibility);return()=>{stopped=true;clearInterval(timer);document.removeEventListener('visibilitychange',onVisibility)}},[!!session]);
 const goto=(x:Tab)=>{haptic();setTab(x);scrollTo({top:0,behavior:'smooth'})};
 if(splash)return <StartupSplash locale={locale} startup={startup} onRetry={()=>location.reload()} t={t}/>;
 if(directWebBlocked)return <DirectWebGate locale={locale}/>;
 if(!session)return <StateScreen title="Chameleon Detailing" text={startup.error||t('errors.startup')} action={()=>location.reload()} actionLabel={t('common.retry')}/>;
 if(session.blocked)return <StateScreen title={t('blacklist.title')} text={session.blockedReason||t('blacklist.text')} action={()=>openBot()} actionLabel={t('common.support')}/>;
 if(session.maintenance&&session.user.role!=='OWNER')return <StateScreen title={t('maintenance.title')} text={t('maintenance.text')} action={()=>location.reload()} actionLabel={t('common.retry')}/>;
 return <div className="app"><SeasonalDecor theme={session.theme?.seasonalTheme}/>
  <header><div className="brand"><img className="logo" src="/brand/chameleon-logo.webp" alt="Chameleon Detailing"/><div><b>Chameleon Detailing</b><span>{t('common.miniApp')}</span></div></div><button className="pill" aria-label={t('profile.language')} onClick={()=>setLocale(locale==='uk'?'pl':locale==='pl'?'en':'uk')}><Globe2 size={16}/>{localeLabels[locale]}</button></header>
  <main>
   {!session.schedule.isOpen&&<HolidayBanner t={t} schedule={session.schedule} locale={locale}/>}
   {tab==='home'&&<HomePage t={t} services={services} goto={goto} currency={currency} content={content}/>}
   {tab==='services'&&<ServicesPage t={t} services={services} goto={goto} currency={currency}/>}
   {tab==='calculator'&&<CalculatorPage t={t} services={services} options={serviceOptions} currency={currency} schedule={session.schedule}/>}
   {tab==='vip'&&<VipPage t={t} tier={session.user.tier}/>}
   {tab==='profile'&&<ProfilePage t={t} session={session} locale={locale} setLocale={setLocale} currency={currency} setCurrency={setCurrency} goto={goto}/>}
   {tab==='orders'&&<OrdersPage t={t} currency={currency}/>}
  </main>
  <nav aria-label="Primary">{([['home',Home,t('nav.home')],['services',Sparkles,t('nav.services')],['calculator',Calculator,t('nav.calculator')],['vip',Crown,t('nav.vip')],['profile',UserRound,t('nav.profile')]] as any).map(([id,I,label]:any)=><button className={tab===id?'active':''} onClick={()=>goto(id)} key={id}><I/><span>{label}</span></button>)}</nav>
 </div>
}
function SeasonalDecor({theme}:{theme?:SeasonalTheme}){
 const key=((theme||'DEFAULT').toUpperCase()) as Exclude<SeasonalTheme,undefined>;
 const icons=seasonalDecorIcons[key]||[];
 if(!icons.length)return null;
 return <div className={`seasonal-decor seasonal-${key.toLowerCase().replace(/_/g,'-')}`} aria-hidden="true">{seasonalDecorPlacements.map((p,idx)=><span key={idx} className="seasonal-decor-item" style={{left:p.left,top:p.top,fontSize:`${p.size}px`,animationDuration:`${p.dur}s`,animationDelay:`${p.delay}s`,opacity:p.alpha}}>{icons[idx%icons.length]}</span>)}</div>}
function DirectWebGate({locale}:{locale:Locale}){const copy={uk:{title:'Найкраще працює прямо в Telegram',text:'Цей веб-вхід зараз закритий. Відкрий Chameleon Detailing у Telegram — там доступні твій профіль, заявки, персональні умови та всі можливості сервісу.',button:'Відкрити в Telegram'},pl:{title:'Najlepiej działa bezpośrednio w Telegramie',text:'Dostęp przez zwykły link jest teraz wyłączony. Otwórz Chameleon Detailing w Telegramie — tam znajdziesz swój profil, zlecenia i pełną funkcjonalność.',button:'Otwórz w Telegramie'},en:{title:'Best experienced directly in Telegram',text:'Direct web access is currently turned off. Open Chameleon Detailing in Telegram for your profile, requests, personal offers and the full experience.',button:'Open in Telegram'}}[locale];return <div className="web-gate"><div className="web-gate-glow"/><div className="web-gate-card"><img src="/brand/chameleon-logo.webp" alt="Chameleon Detailing"/><span className="eyebrow">CHAMELEON DETAILING</span><h1>{copy.title}</h1><p>{copy.text}</p><button className="primary" onClick={()=>openBot()}><MessageCircle/><span>{copy.button}</span><ChevronRight/></button></div></div>}
function StartupSplash({locale,startup,onRetry,t}:any){const stageKey:{[k:string]:TranslationKey}={INIT:'loading.init',AUTH:'loading.auth',PROFILE:'loading.profile',CONFIG:'loading.config',READY:'loading.ready'};return <div className={`startup-splash ${startup.stage==='READY'?'ready':''}`}><div className="splash-glow"/><img src="/brand/chameleon-logo.webp" className="splash-logo" alt=""/><h1>Chameleon Detailing</h1><div className="startup-progress"><i style={{width:`${startup.progress}%`}}/></div><b className="startup-stage">{t(stageKey[startup.stage]||'loading.init')}</b><p>{splashSlogan[locale as Locale]||splashSlogan.en}</p>{startup.error&&<div className="startup-error"><TriangleAlert/><span>{startup.error}</span><button onClick={onRetry}>{t('common.retry')}</button></div>}</div>}
function StateScreen({title,text,action,actionLabel}:any){return <div className="state-screen"><img src="/brand/chameleon-logo.webp" className="logo xl" alt=""/><h1>{title}</h1><p>{text}</p>{action&&<button className="primary" onClick={action}>{actionLabel}</button>}</div>}
function HolidayBanner({t,schedule,locale}:any){return <div className="holiday-banner"><Clock3/><div><b>{t('holiday.title')}</b><span>{t('holiday.text')}{schedule.nextWorkingAt?` · ${new Date(schedule.nextWorkingAt).toLocaleString(locale==='uk'?'uk-UA':locale==='pl'?'pl-PL':'en-US')}`:''}</span></div></div>}
function ServiceArt({service,small=false}:{service:Partial<Service>;small?:boolean}){return <div className={`service-art${small?' small':''}`}>{service.imageUrl?<img className="service-art-image" src={service.imageUrl} alt={service.title||service.slug||'Service'}/>:<Sparkles/>}</div>}
function HomePage({t,services,goto,currency,content}:any){const [sharing,setSharing]=useState(false);const referralTitle=content?.['referral.title']||t('home.referral'),referralSubtitle=content?.['referral.subtitle']||t('home.referralSubtitle'),referralShare=content?.['referral.share_text']||t('home.referralShare');const invite=async()=>{if(sharing)return;haptic();setSharing(true);try{const r=await api.referral();shareTelegramLink(r.url,referralShare);notify('success')}catch{notify('error')}finally{setSharing(false)}};return <><section className="hero"><div className="hero-copy"><div className="eyebrow">{t('home.eyebrow')}</div><h1>{t('home.hero')}</h1><p>{t('home.subtitle')}</p><button className="primary" onClick={()=>goto('calculator')}><Calculator/> <span>{t('home.calculate')}</span><ChevronRight/></button></div><div className="hero-mascot" aria-hidden="true"><img src="/brand/chameleon-logo.webp" alt=""/></div><div className="hero-badges"><span><ShieldCheck/>{t('home.benefitClean')}</span><span><Droplets/>{t('home.benefitProtection')}</span><span><Gem/>{t('home.benefitPremium')}</span></div></section><section><div className="section-title"><h2>{t('home.popular')}</h2><button onClick={()=>goto('services')}>{t('nav.services')}<ChevronRight/></button></div><div className="service-grid">{services.filter((s:any)=>Boolean(s.isPopular)).slice(0,4).map((s:any)=><article className="service-card" key={s.slug}><ServiceArt service={s}/><div><h3>{s.title}</h3><p>{s.description}</p><b>{t('home.from')} {money(s.basePrice,s.currency||currency)}</b>{s.standardBasePrice!=null&&Number(s.standardBasePrice)!==Number(s.basePrice)&&<small className="vip-price-note">{s.promotion?`🏷 -${s.promotion.percentDiscount}%`:`💎 ${t('vip.activePrice')}`} · <del>{money(s.standardBasePrice,s.currency||currency)}</del></small>}</div></article>)}</div></section><button className="ref-card referral-button" onClick={invite} disabled={sharing} aria-busy={sharing}><Gift/><div><h3>{referralTitle}</h3><p>{sharing?t('home.referralPreparing'):referralSubtitle}</p></div>{sharing?<Loader2 className="spin"/>:<ChevronRight/>}</button></>}
function ServicesPage({t,services,goto,currency}:any){return <section><div className="page-head"><span>02</span><div><h1>{t('services.title')}</h1><p>{t('services.subtitle')}</p></div></div><div className="stack">{services.map((s:any)=><article className="list-card" key={s.slug}><ServiceArt service={s} small/><div className="grow"><h3>{s.title}</h3><p>{s.description}</p><b>{t('home.from')} {money(s.basePrice,s.currency||currency)} · {s.durationMin} {t('common.minutes')}</b>{s.standardBasePrice!=null&&Number(s.standardBasePrice)!==Number(s.basePrice)&&<small className="vip-price-note">{s.promotion?`🏷 -${s.promotion.percentDiscount}%`:`💎 ${t('vip.activePrice')}`} · <del>{money(s.standardBasePrice,s.currency||currency)}</del></small>}</div><button className="icon-btn" aria-label={t('home.calculate')} onClick={()=>goto('calculator')}><ChevronRight/></button></article>)}</div></section>}
function CalculatorPage({t,services,options,currency,schedule}:any){
 const [step,setStep]=useState(1),[service,setService]=useState(services[0]?.slug||''),[vehicle,setVehicle]=useState('sedan'),[condition,setCondition]=useState('normal'),[extra,setExtra]=useState<string[]>([]),[quote,setQuote]=useState<any>(null),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[processing,setProcessing]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''); const timers=useRef<any[]>([]);
 useEffect(()=>{if(!service&&services[0])setService(services[0].slug)},[services,service]); useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 const calculate=async()=>{setBusy(true);setError('');setProcessing(true);setStatus(t('calculator.processing1'));const started=Date.now();timers.current=[setTimeout(()=>setStatus(t('calculator.processing2')),260),setTimeout(()=>setStatus(t('calculator.processing3')),520)];try{const q=await api.quote({service,vehicle,condition,options:extra,currency});const left=motion.calculatorOverlayMin-(Date.now()-started);if(left>0)await wait(left);setStatus(t('calculator.ready'));await wait(160);setQuote(q);setProcessing(false);notify('success')}catch(e:unknown){setError(friendlyError(e,t));setProcessing(false);notify('error')}finally{setBusy(false)}};
 const next=()=>step<4?setStep(step+1):calculate();
 const send=async(requestType='STANDARD')=>{setBusy(true);setError('');try{await api.request({service,vehicle,condition,options:extra,currency,requestType});setSent(true);notify('success')}catch(e:unknown){setError(friendlyError(e,t));notify('error')}finally{setBusy(false)}};
 const title=step===1?t('calculator.need'):step===2?t('calculator.vehicle'):step===3?t('calculator.condition'):t('calculator.extras');
 return <section><div className="calc-top"><div className="steps">{[1,2,3,4].map(n=><i className={n<=step?'on':''} key={n}>{n<step?<Check/>:n}</i>)}</div><h1>{title}</h1></div>
 {step===1&&<div className="choice-list">{services.map((s:any)=><Choice key={s.slug} on={()=>setService(s.slug)} active={service===s.slug} title={s.title} sub={s.description}/>)}</div>}
 {step===2&&<div className="choice-list vehicle-choice-list">{vehicles.map(([id,key,image])=><Choice key={id} on={()=>setVehicle(id)} active={vehicle===id} title={t(key)} icon={<img className="vehicle-choice-image" src={image} alt={t(key)}/>}/>)}</div>}
 {step===3&&<div className="choice-list">{conditions.map(([id,key])=><Choice key={id} on={()=>setCondition(id)} active={condition===id} title={t(key)}/>)}</div>}
 {step===4&&<div className="choice-list">{(options||[]).map((opt:ServiceOption)=><Choice key={opt.slug} on={()=>setExtra(extra.includes(opt.slug)?extra.filter(x=>x!==opt.slug):[...extra,opt.slug])} active={extra.includes(opt.slug)} title={opt.title} sub={`${opt.description?opt.description+' · ':''}+ ${money(opt.price,opt.currency||currency)}`}/>)}</div>}
 <div className="calc-actions">{step>1&&<button className="secondary" aria-label={t('common.back')} onClick={()=>setStep(step-1)}><ArrowLeft/></button>}<button className="primary grow" onClick={next} disabled={busy}>{busy?<Loader2 className="spin"/>:<span>{step===4?t('home.calculate'):t('common.continue')}</span>}<ChevronRight/></button></div>
 {processing&&<ProcessingOverlay t={t} status={status}/>} {quote&&<ResultModal t={t} q={quote} sent={sent} busy={busy} error={error} schedule={schedule} onClose={()=>setQuote(null)} onEdit={()=>{setQuote(null);setStep(1)}} onSend={send}/>} {error&&!quote&&!processing&&<div className="inline-error"><TriangleAlert/>{error}</div>}
 </section>}
function ProcessingOverlay({t,status}:any){return <div className="overlay-backdrop"><div className="processing-card"><img src="/brand/chameleon-logo.webp" alt=""/><h3>{t('calculator.processing')}</h3><div className="loader-bar"><i/></div><p>{status}</p></div></div>}
function ResultModal({t,q,sent,busy,error,schedule,onClose,onEdit,onSend}:any){const standardTotal=Number(q.standardTotal??0);const discountLabel=q.discountSource==='PERSONAL'?t('calculator.personalGift'):q.discountSource==='PROMOTION'?t('calculator.promotion'):t('calculator.vipDiscount');const ep=q.emergencyPreview;const emPct=ep?Math.round((Number(ep.multiplier||1)-1)*100):0;return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="result-modal"><button className="modal-close" aria-label={t('common.close')} onClick={onClose}><X/></button><span className="eyebrow">✨ {t('calculator.result')}</span><strong>{money(q.finalPrice,q.currency)}</strong>{q.discount>0&&standardTotal>0&&<small className="result-note"><del>{money(standardTotal,q.currency)}</del> · {discountLabel}</small>}<div className="breakdown"><p><span>{t('common.base')}</span><b>{money(q.basePrice,q.currency)}</b></p><p><span>{t('common.vehicle')}</span><b>× {q.vehicleMultiplier}</b></p><p><span>{t('common.condition')}</span><b>× {q.conditionMultiplier}</b></p><p><span>{t('common.options')}</span><b>{money(q.optionsTotal,q.currency)}</b></p>{q.discount>0&&<p className="lime"><span>{discountLabel}</span><b>-{money(q.discount,q.currency)}</b></p>}<p className="lime total-row"><span>{t('common.total')}</span><b>{money(q.finalPrice,q.currency)}</b></p>{ep&&<><p className="emergency-row"><span>{t('calculator.emergencyExtra')} · ×{Number(ep.multiplier).toFixed(2)} (+{emPct}%)</span><b>+{money(ep.surcharge,ep.currency||q.currency)}</b></p><p className="emergency-total"><span>{t('calculator.emergencyTotal')}</span><b>{money(ep.finalPrice,ep.currency||q.currency)}</b></p></>}</div>{q.fxTimestamp&&<small>{t('common.fx')}: {new Date(q.fxTimestamp).toLocaleString()}</small>}{ep&&<small className="emergency-hint">{t('calculator.emergencyHint')}</small>}{sent?<div className="success"><Check/>{t('calculator.sent')}</div>:<div className="modal-actions">{schedule.isOpen?<button className="primary" onClick={()=>onSend('STANDARD')} disabled={busy}>{t('calculator.send')}</button>:<><button className="primary" onClick={()=>onSend('DEFERRED')} disabled={busy}>{t('calculator.deferred')}</button>{schedule.emergencyEnabled&&ep&&<button className="warning-btn emergency-order-btn" onClick={()=>onSend('EMERGENCY')} disabled={busy}><span>{t('calculator.emergency')}</span></button>}</>}<button className="secondary wide" onClick={onEdit}>{t('calculator.edit')}</button></div>}{error&&<div className="inline-error"><TriangleAlert/>{error}</div>}</div></div>}
function Choice({active,on,title,sub,icon}:any){return <button className={`choice ${active?'selected':''}`} onClick={()=>{haptic();on()}}>{icon&&<span className="choice-icon">{icon}</span>}<span className="grow"><b>{title}</b>{sub&&<small>{sub}</small>}</span><i>{active?<Check/>:<ChevronRight/>}</i></button>}
function VipPage({t,tier}:any){const tierLabel=(tier||t('common.standard')).toUpperCase();return <section className="vip-section"><div className="vip-card"><div className="vip-orbit" aria-hidden="true"><i/><i/></div><div className="vip-topline"><div className="vip-wordmark"><strong>CHAMELEON</strong><span>DETAILING</span></div><div className="vip-tagline">{t('vip.tagline')}<i/></div></div><div className="vip-content"><span className="vip-eyebrow">{t('vip.status')}</span><h1>Chameleon</h1><i className="vip-accent"/><p>{t('vip.text')}</p><div className="vip-tier"><Crown/><i/><b>{tierLabel}</b></div></div><div className="vip-footer"><span>{t('vip.footer')}</span><div><i/>{t('vip.footerRight')}</div></div></div></section>}
function OrdersPage({t,currency}:any){
 const [orders,setOrders]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[deleting,setDeleting]=useState<number|null>(null);
 const load=async()=>{setBusy(true);setError('');try{const r=await api.orders();setOrders(r.orders||[])}catch(e:unknown){setError(e instanceof Error?e.message:t('errors.generic'))}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const statusKey=(status:string)=>{const k=String(status||'REQUESTED').toUpperCase();const map:any={REQUESTED:'orders.status.requested',PENDING_CONFIRMATION:'orders.status.requested',CONFIRMED:'orders.status.confirmed',IN_PROGRESS:'orders.status.inProgress',COMPLETED:'orders.status.completed',COMPLETED_UNPAID:'orders.status.completedUnpaid',PAID:'orders.status.paid',REJECTED:'orders.status.rejected',CANCELLED:'orders.status.cancelled',DEFERRED:'orders.status.deferred'};return map[k]||'orders.status.requested'};
 const statusHint=(status:string)=>{const k=String(status||'REQUESTED').toUpperCase();const map:any={REQUESTED:'orders.hint.requested',PENDING_CONFIRMATION:'orders.hint.requested',CONFIRMED:'orders.hint.confirmed',IN_PROGRESS:'orders.hint.inProgress',COMPLETED:'orders.hint.completed',COMPLETED_UNPAID:'orders.hint.completedUnpaid',PAID:'orders.hint.paid',REJECTED:'orders.hint.rejected',CANCELLED:'orders.hint.cancelled',DEFERRED:'orders.hint.deferred'};return map[k]||'orders.hint.requested'};
 const canDelete=(status:string)=>['REQUESTED','PENDING_CONFIRMATION','REJECTED','CANCELLED','DEFERRED'].includes(String(status||'').toUpperCase());
 const remove=async(id:number)=>{if(!confirm(t('orders.deleteConfirm')))return;setDeleting(id);setError('');try{await api.deleteOrder(id);notify('success');setOrders(x=>x.filter(o=>o.id!==id))}catch(e:unknown){setError(e instanceof Error?e.message:t('errors.generic'));notify('error')}finally{setDeleting(null)}};
 return <section><div className="page-head"><span>📋</span><div><h1>{t('orders.title')}</h1><p>{t('orders.subtitle')}</p></div></div><button className="secondary wide orders-refresh" onClick={load} disabled={busy}>{busy?<Loader2 className="spin"/>:<RefreshCw/>}<span>{t('orders.refresh')}</span></button>{error&&<div className="inline-error"><TriangleAlert/>{error}</div>}<div className="stack orders-stack">{!busy&&orders.length===0&&<div className="empty-card"><ClipboardList/><p>{t('orders.empty')}</p></div>}{orders.map((o:any)=><article className="order-card" key={o.id}><div className="order-card-top"><div><span className="eyebrow">{t('orders.requestId')} #{o.id}</span><h3>{o.service_slug||'Chameleon Detailing'}</h3></div><b className={`order-status status-${String(o.status||'REQUESTED').toLowerCase()}`}>{t(statusKey(o.status) as TranslationKey)}</b></div><p className="order-status-hint">{t(statusHint(o.status) as TranslationKey)}</p><div className="order-meta"><span>{t('orders.type')}<b>{o.request_type||'STANDARD'}</b></span><span>{t('orders.payment')}<b>{o.payment_status||'PENDING'}</b></span><span>{t('orders.created')}<b>{o.created_at?new Date(o.created_at+'Z').toLocaleString(): '—'}</b></span>{o.scheduled_for&&<span>{t('orders.scheduled')}<b>{new Date(o.scheduled_for).toLocaleString()}</b></span>}</div><div className="order-price">{money(o.final_job_price??o.calculated_price,o.currency||currency)}</div>{Array.isArray(o.extra_services)&&o.extra_services.length>0&&<div className="order-extra-services">{o.extra_services.map((x:any,i:number)=><span key={i}>➕ {x.title} · {money(x.price,x.currency||o.currency||currency)}</span>)}</div>}{o.price_adjustment_reason&&<p className="order-adjustment-note">{o.price_adjustment_reason}</p>}{canDelete(o.status)&&<button className="danger-link" onClick={()=>remove(o.id)} disabled={deleting===o.id}>{deleting===o.id?<Loader2 className="spin"/>:<Trash2/>}<span>{t('orders.delete')}</span></button>}</article>)}</div></section>
}
function ProfilePage({t,session,locale,setLocale,currency,setCurrency,goto}:any){const changeCurrency=async(next:string)=>{const value=next.toUpperCase();setCurrency(value);try{await api.setCurrency(value);notify('success')}catch{notify('error')}};return <section><div className="profile-card"><div className="avatar"><img src={session.user.photoUrl||api.profilePhotoUrl()} alt={session.user.firstName||'Telegram profile'} onError={e=>{const img=e.currentTarget;img.style.display='none';const fallback=img.nextElementSibling as HTMLElement|null;if(fallback)fallback.style.display='grid'}}/><span style={{display:'none'}}>{(session.user.firstName||'C')[0]}</span></div><div className="grow"><h2>{session.user.firstName}</h2><p>{session.user.username?'@'+session.user.username:t('common.telegramUser')}</p><small>{t('profile.role')}: {t((`role.${session.user.role}` as TranslationKey))}</small></div></div><div className="settings-card"><label><Globe2/><span>{t('profile.language')}</span><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="uk">{localeNames.uk}</option><option value="pl">{localeNames.pl}</option><option value="en">{localeNames.en}</option></select></label><label><Gem/><span>{t('profile.currency')}</span><select value={currency} onChange={e=>changeCurrency(e.target.value)}><option>PLN</option><option>USD</option><option>UAH</option></select></label><button className="profile-action" onClick={()=>goto('orders')}><ClipboardList/><span><b>{t('profile.requests')}</b><small>{t('profile.requestsHint')}</small></span><ChevronRight/></button><button className="profile-action" onClick={()=>openBot()}><MessageCircle/><span><b>{t('profile.chat')}</b><small>{t('profile.chatHint')}</small></span><ChevronRight/></button></div></section>}
const previewFx:Record<string,Record<string,number>>={PLN:{PLN:1,USD:.26,UAH:11.1},USD:{USD:1,PLN:3.85,UAH:42.7},UAH:{UAH:1,PLN:.09,USD:.0234}};
const convertPreview=(v:number,from:string,to:string)=>Number(v||0)*(previewFx[from]?.[to]||1);
const money=(v:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c||'PLN',maximumFractionDigits:2}).format(Number(v||0));
