import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Home,Sparkles,Calculator,Crown,UserRound,ChevronRight,Car,ShieldCheck,Droplets,Gem,Gift,Globe2,Check,ArrowLeft,Loader2,MessageCircle,Clock3,X,TriangleAlert,ClipboardList,RefreshCw} from 'lucide-react';
import {api,Service,Session} from './lib/api';
import {haptic,initTelegram,notify,openBot,shareTelegramLink,telegramLanguage} from './lib/telegram';
import {createTranslator,Locale,localeLabels,localeNames,normalizeLocale,splashSlogan,TranslationKey} from './locales';
import {motion} from './config/motion';

type Tab='home'|'services'|'calculator'|'vip'|'profile'|'orders';
const vehicles=[['sedan','vehicle.sedan'],['hatchback','vehicle.hatchback'],['suv','vehicle.suv'],['large-suv','vehicle.largeSuv'],['van','vehicle.van']] as const;
const conditions=[['light','condition.light'],['normal','condition.normal'],['dirty','condition.dirty'],['very-dirty','condition.veryDirty']] as const;
const options=[['pet-hair','option.petHair',30],['ceramic-spray','option.ceramicSpray',40],['odor','option.odor',25]] as const;
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const friendlyError=(e:unknown,t:(key:TranslationKey)=>string)=>{const m=e instanceof Error?e.message:String(e||'');if(/BOT_TOKEN/i.test(m))return t('errors.botToken');if(/Invalid or expired Telegram session/i.test(m))return t('errors.telegramSession');if(/maintenance/i.test(m))return t('errors.maintenance');if(/Access limited/i.test(m))return t('errors.accessLimited');if(/outside working hours/i.test(m))return t('errors.outsideHours');if(/Emergency mode/i.test(m))return t('errors.emergencyUnavailable');if(/60 minutes/i.test(m))return t('errors.rateLimit');return t('errors.generic')};

export function App(){
 const initialTab=useMemo<Tab>(()=>{const v=new URLSearchParams(location.search).get('startapp');return v==='calculator'||v==='orders'?v:'home'},[]);
 const [session,setSession]=useState<Session|null>(null),[services,setServices]=useState<Service[]>([]),[content,setContent]=useState<Record<string,string>>({}),[tab,setTab]=useState<Tab>(initialTab);
 const initialLocale=useMemo(()=>normalizeLocale(localStorage.getItem('chameleon.locale')||telegramLanguage()),[]);
 const [locale,setLocaleState]=useState<Locale>(initialLocale),[currency,setCurrency]=useState('PLN');
 const [startup,setStartup]=useState({stage:'INIT',progress:15,error:''}),[splash,setSplash]=useState(true);
 const t=useMemo(()=>createTranslator(locale),[locale]);
 const setLocale=(next:Locale)=>{localStorage.setItem('chameleon.locale',next);setLocaleState(next)};
 useEffect(()=>{document.documentElement.lang=locale},[locale]);
 useEffect(()=>{initTelegram();(async()=>{const started=Date.now();try{
   setStartup({stage:'AUTH',progress:35,error:''}); const s=await api.session();
   setStartup({stage:'PROFILE',progress:55,error:''}); const saved=localStorage.getItem('chameleon.locale');const resolved=normalizeLocale(saved||s.user.locale||telegramLanguage()); const resolvedCurrency=(s.user.currency||'PLN').toUpperCase(); setLocale(resolved); setCurrency(resolvedCurrency); setSession(s);
   setStartup({stage:'CONFIG',progress:80,error:''}); const [sv,ct]=await Promise.all([api.services(resolved,resolvedCurrency),api.content(resolved)]); setServices(sv.services);setContent(ct.content||{});
   setStartup({stage:'READY',progress:100,error:''}); const elapsed=Date.now()-started;if(elapsed<motion.splashMin)await wait(motion.splashMin-elapsed);await wait(160);setSplash(false);
  }catch(e:unknown){setStartup(x=>({...x,error:friendlyError(e,t)}));}})()},[]);
 useEffect(()=>{if(!session)return;Promise.all([api.services(locale,currency),api.content(locale)]).then(([x,ct])=>{setServices(x.services);setContent(ct.content||{})}).catch(()=>{})},[locale,currency,session]);
 const goto=(x:Tab)=>{haptic();setTab(x);scrollTo({top:0,behavior:'smooth'})};
 if(splash)return <StartupSplash locale={locale} startup={startup} onRetry={()=>location.reload()} t={t}/>;
 if(!session)return <StateScreen title="Chameleon Detailing" text={startup.error||t('errors.startup')} action={()=>location.reload()} actionLabel={t('common.retry')}/>;
 if(session.blocked)return <StateScreen title={t('blacklist.title')} text={session.blockedReason||t('blacklist.text')} action={()=>openBot()} actionLabel={t('common.support')}/>;
 if(session.maintenance&&session.user.role!=='OWNER')return <StateScreen title={t('maintenance.title')} text={t('maintenance.text')} action={()=>location.reload()} actionLabel={t('common.retry')}/>;
 return <div className="app">
  <header><div className="brand"><img className="logo" src="/brand/chameleon-logo.webp" alt="Chameleon Detailing"/><div><b>Chameleon Detailing</b><span>{t('common.miniApp')}</span></div></div><button className="pill" aria-label={t('profile.language')} onClick={()=>setLocale(locale==='uk'?'pl':locale==='pl'?'en':'uk')}><Globe2 size={16}/>{localeLabels[locale]}</button></header>
  <main>
   {!session.schedule.isOpen&&<HolidayBanner t={t} schedule={session.schedule} locale={locale}/>} 
   {tab==='home'&&<HomePage t={t} services={services} goto={goto} currency={currency} content={content}/>} 
   {tab==='services'&&<ServicesPage t={t} services={services} goto={goto} currency={currency}/>} 
   {tab==='calculator'&&<CalculatorPage t={t} services={services} currency={currency} schedule={session.schedule}/>} 
   {tab==='vip'&&<VipPage t={t} tier={session.user.tier}/>} 
   {tab==='profile'&&<ProfilePage t={t} session={session} locale={locale} setLocale={setLocale} currency={currency} setCurrency={setCurrency} goto={goto}/>} 
   {tab==='orders'&&<OrdersPage t={t} currency={currency}/>} 
  </main>
  <nav aria-label="Primary">{([['home',Home,t('nav.home')],['services',Sparkles,t('nav.services')],['calculator',Calculator,t('nav.calculator')],['vip',Crown,t('nav.vip')],['profile',UserRound,t('nav.profile')]] as any).map(([id,I,label]:any)=><button className={tab===id?'active':''} onClick={()=>goto(id)} key={id}><I/><span>{label}</span></button>)}</nav>
 </div>
}
function StartupSplash({locale,startup,onRetry,t}:any){const stageKey:{[k:string]:TranslationKey}={INIT:'loading.init',AUTH:'loading.auth',PROFILE:'loading.profile',CONFIG:'loading.config',READY:'loading.ready'};return <div className={`startup-splash ${startup.stage==='READY'?'ready':''}`}><div className="splash-glow"/><img src="/brand/chameleon-logo.webp" className="splash-logo" alt=""/><h1>Chameleon Detailing</h1><div className="startup-progress"><i style={{width:`${startup.progress}%`}}/></div><b className="startup-stage">{t(stageKey[startup.stage]||'loading.init')}</b><p>{splashSlogan[locale as Locale]||splashSlogan.en}</p>{startup.error&&<div className="startup-error"><TriangleAlert/><span>{startup.error}</span><button onClick={onRetry}>{t('common.retry')}</button></div>}</div>}
function StateScreen({title,text,action,actionLabel}:any){return <div className="state-screen"><img src="/brand/chameleon-logo.webp" className="logo xl" alt=""/><h1>{title}</h1><p>{text}</p>{action&&<button className="primary" onClick={action}>{actionLabel}</button>}</div>}
function HolidayBanner({t,schedule,locale}:any){return <div className="holiday-banner"><Clock3/><div><b>{t('holiday.title')}</b><span>{t('holiday.text')}{schedule.nextWorkingAt?` · ${new Date(schedule.nextWorkingAt).toLocaleString(locale==='uk'?'uk-UA':locale==='pl'?'pl-PL':'en-US')}`:''}</span></div></div>}
function HomePage({t,services,goto,currency,content}:any){const [sharing,setSharing]=useState(false);const referralTitle=content?.['referral.title']||t('home.referral'),referralSubtitle=content?.['referral.subtitle']||t('home.referralSubtitle'),referralShare=content?.['referral.share_text']||t('home.referralShare');const invite=async()=>{if(sharing)return;haptic();setSharing(true);try{const r=await api.referral();shareTelegramLink(r.url,referralShare);notify('success')}catch{notify('error')}finally{setSharing(false)}};return <><section className="hero"><div className="hero-copy"><div className="eyebrow">{t('home.eyebrow')}</div><h1>{t('home.hero')}</h1><p>{t('home.subtitle')}</p><button className="primary" onClick={()=>goto('calculator')}><Calculator/> <span>{t('home.calculate')}</span><ChevronRight/></button></div><div className="hero-mascot" aria-hidden="true"><img src="/brand/chameleon-logo.webp" alt=""/></div><div className="hero-badges"><span><ShieldCheck/>{t('home.benefitClean')}</span><span><Droplets/>{t('home.benefitProtection')}</span><span><Gem/>{t('home.benefitPremium')}</span></div></section><section><div className="section-title"><h2>{t('home.popular')}</h2><button onClick={()=>goto('services')}>{t('nav.services')}<ChevronRight/></button></div><div className="service-grid">{services.slice(0,4).map((s:any)=><article className="service-card" key={s.slug}><div className="service-art"><Car/></div><div><h3>{s.title}</h3><p>{s.description}</p><b>{t('home.from')} {money(s.basePrice,s.currency||currency)}</b>{s.standardBasePrice!=null&&Number(s.standardBasePrice)!==Number(s.basePrice)&&<small className="vip-price-note">💎 {t('vip.activePrice')} · <del>{money(s.standardBasePrice,s.currency||currency)}</del></small>}</div></article>)}</div></section><button className="ref-card referral-button" onClick={invite} disabled={sharing} aria-busy={sharing}><Gift/><div><h3>{referralTitle}</h3><p>{sharing?t('home.referralPreparing'):referralSubtitle}</p></div>{sharing?<Loader2 className="spin"/>:<ChevronRight/>}</button></>}
function ServicesPage({t,services,goto,currency}:any){return <section><div className="page-head"><span>02</span><div><h1>{t('services.title')}</h1><p>{t('services.subtitle')}</p></div></div><div className="stack">{services.map((s:any)=><article className="list-card" key={s.slug}><div className="service-art small"><Sparkles/></div><div className="grow"><h3>{s.title}</h3><p>{s.description}</p><b>{t('home.from')} {money(s.basePrice,s.currency||currency)} · {s.durationMin} {t('common.minutes')}</b>{s.standardBasePrice!=null&&Number(s.standardBasePrice)!==Number(s.basePrice)&&<small className="vip-price-note">💎 {t('vip.activePrice')} · <del>{money(s.standardBasePrice,s.currency||currency)}</del></small>}</div><button className="icon-btn" aria-label={t('home.calculate')} onClick={()=>goto('calculator')}><ChevronRight/></button></article>)}</div></section>}
function CalculatorPage({t,services,currency,schedule}:any){
 const [step,setStep]=useState(1),[service,setService]=useState(services[0]?.slug||''),[vehicle,setVehicle]=useState('sedan'),[condition,setCondition]=useState('normal'),[extra,setExtra]=useState<string[]>([]),[quote,setQuote]=useState<any>(null),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[processing,setProcessing]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''); const timers=useRef<any[]>([]);
 useEffect(()=>{if(!service&&services[0])setService(services[0].slug)},[services,service]); useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
 const calculate=async()=>{setBusy(true);setError('');setProcessing(true);setStatus(t('calculator.processing1'));const started=Date.now();timers.current=[setTimeout(()=>setStatus(t('calculator.processing2')),260),setTimeout(()=>setStatus(t('calculator.processing3')),520)];try{const q=await api.quote({service,vehicle,condition,options:extra,currency});const left=motion.calculatorOverlayMin-(Date.now()-started);if(left>0)await wait(left);setStatus(t('calculator.ready'));await wait(160);setQuote(q);setProcessing(false);notify('success')}catch(e:unknown){setError(friendlyError(e,t));setProcessing(false);notify('error')}finally{setBusy(false)}};
 const next=()=>step<4?setStep(step+1):calculate();
 const send=async(requestType='STANDARD')=>{setBusy(true);setError('');try{await api.request({service,vehicle,condition,options:extra,currency,requestType});setSent(true);notify('success')}catch(e:unknown){setError(t('errors.request'));notify('error')}finally{setBusy(false)}};
 const title=step===1?t('calculator.need'):step===2?t('calculator.vehicle'):step===3?t('calculator.condition'):t('calculator.extras');
 return <section><div className="calc-top"><div className="steps">{[1,2,3,4].map(n=><i className={n<=step?'on':''} key={n}>{n<step?<Check/>:n}</i>)}</div><h1>{title}</h1></div>
 {step===1&&<div className="choice-list">{services.map((s:any)=><Choice key={s.slug} on={()=>setService(s.slug)} active={service===s.slug} title={s.title} sub={s.description}/>)}</div>}
 {step===2&&<div className="choice-grid">{vehicles.map(([id,key])=><Choice key={id} on={()=>setVehicle(id)} active={vehicle===id} title={t(key)} icon={<Car/>}/>)}</div>}
 {step===3&&<div className="choice-list">{conditions.map(([id,key])=><Choice key={id} on={()=>setCondition(id)} active={condition===id} title={t(key)}/>)}</div>}
 {step===4&&<div className="choice-list">{options.map(([id,key,price])=><Choice key={id} on={()=>setExtra(extra.includes(id)?extra.filter(x=>x!==id):[...extra,id])} active={extra.includes(id)} title={t(key)} sub={`+ ${money(convertPreview(price,'PLN',currency),currency)}`}/>)}</div>}
 <div className="calc-actions">{step>1&&<button className="secondary" aria-label={t('common.back')} onClick={()=>setStep(step-1)}><ArrowLeft/></button>}<button className="primary grow" onClick={next} disabled={busy}>{busy?<Loader2 className="spin"/>:<span>{step===4?t('home.calculate'):t('common.continue')}</span>}<ChevronRight/></button></div>
 {processing&&<ProcessingOverlay t={t} status={status}/>} {quote&&<ResultModal t={t} q={quote} sent={sent} busy={busy} error={error} schedule={schedule} onClose={()=>setQuote(null)} onEdit={()=>{setQuote(null);setStep(1)}} onSend={send}/>} {error&&!quote&&!processing&&<div className="inline-error"><TriangleAlert/>{error}</div>}
 </section>}
function ProcessingOverlay({t,status}:any){return <div className="overlay-backdrop"><div className="processing-card"><img src="/brand/chameleon-logo.webp" alt=""/><h3>{t('calculator.processing')}</h3><div className="loader-bar"><i/></div><p>{status}</p></div></div>}
function ResultModal({t,q,sent,busy,error,schedule,onClose,onEdit,onSend}:any){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="result-modal"><button className="modal-close" aria-label={t('common.close')} onClick={onClose}><X/></button><span className="eyebrow">✨ {t('calculator.result')}</span><strong>{money(q.finalPrice,q.currency)}</strong><div className="breakdown"><p><span>{t('common.base')}</span><b>{money(q.basePrice,q.currency)}</b></p><p><span>{t('common.vehicle')}</span><b>× {q.vehicleMultiplier}</b></p><p><span>{t('common.condition')}</span><b>× {q.conditionMultiplier}</b></p><p><span>{t('common.options')}</span><b>{money(q.optionsTotal,q.currency)}</b></p>{q.discount>0&&<p className="lime"><span>VIP</span><b>-{money(q.discount,q.currency)}</b></p>}</div>{q.fxTimestamp&&<small>{t('common.fx')}: {q.fxProvider} · {new Date(q.fxTimestamp).toLocaleString()}</small>}{sent?<div className="success"><Check/>{t('calculator.sent')}</div>:<div className="modal-actions">{schedule.isOpen?<button className="primary" onClick={()=>onSend('STANDARD')} disabled={busy}>{t('calculator.send')}</button>:<><button className="primary" onClick={()=>onSend('DEFERRED')} disabled={busy}>{t('calculator.deferred')}</button>{schedule.emergencyEnabled&&<button className="warning-btn" onClick={()=>onSend('EMERGENCY')} disabled={busy}>{t('calculator.emergency')} ×{schedule.emergencyMultiplier}</button>}</>}<button className="secondary wide" onClick={onEdit}>{t('calculator.edit')}</button></div>}{error&&<div className="inline-error"><TriangleAlert/>{error}</div>}</div></div>}
function Choice({active,on,title,sub,icon}:any){return <button className={`choice ${active?'selected':''}`} onClick={()=>{haptic();on()}}>{icon&&<span className="choice-icon">{icon}</span>}<span className="grow"><b>{title}</b>{sub&&<small>{sub}</small>}</span><i>{active?<Check/>:<ChevronRight/>}</i></button>}
function VipPage({t,tier}:any){const tierLabel=(tier||t('common.standard')).toUpperCase();return <section className="vip-section"><div className="vip-card"><div className="vip-orbit" aria-hidden="true"><i/><i/></div><div className="vip-topline"><div className="vip-wordmark"><strong>CHAMELEON</strong><span>DETAILING</span></div><div className="vip-tagline">{t('vip.tagline')}<i/></div></div><div className="vip-content"><span className="vip-eyebrow">{t('vip.status')}</span><h1>Chameleon</h1><i className="vip-accent"/><p>{t('vip.text')}</p><div className="vip-tier"><Crown/><i/><b>{tierLabel}</b></div></div><div className="vip-footer"><span>{t('vip.footer')}</span><div><i/>{t('vip.footerRight')}</div></div></div></section>}
function OrdersPage({t,currency}:any){const [orders,setOrders]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');const load=async()=>{setBusy(true);setError('');try{const r=await api.orders();setOrders(r.orders||[])}catch(e:unknown){setError(e instanceof Error?e.message:t('errors.generic'))}finally{setBusy(false)}};useEffect(()=>{load()},[]);return <section><div className="page-head"><span>📋</span><div><h1>{t('orders.title')}</h1><p>{t('orders.subtitle')}</p></div></div><button className="secondary wide orders-refresh" onClick={load} disabled={busy}>{busy?<Loader2 className="spin"/>:<RefreshCw/>}<span>{t('orders.refresh')}</span></button>{error&&<div className="inline-error"><TriangleAlert/>{error}</div>}<div className="stack orders-stack">{!busy&&orders.length===0&&<div className="empty-card"><ClipboardList/><p>{t('orders.empty')}</p></div>}{orders.map((o:any)=><article className="order-card" key={o.id}><div className="order-card-top"><div><span className="eyebrow">{t('orders.requestId')} #{o.id}</span><h3>{o.service_slug||'Chameleon Detailing'}</h3></div><b className={`order-status status-${String(o.status||'REQUESTED').toLowerCase()}`}>{o.status||'REQUESTED'}</b></div><div className="order-meta"><span>{t('orders.type')}<b>{o.request_type||'STANDARD'}</b></span><span>{t('orders.payment')}<b>{o.payment_status||'PENDING'}</b></span><span>{t('orders.created')}<b>{o.created_at?new Date(o.created_at+'Z').toLocaleString(): '—'}</b></span>{o.scheduled_for&&<span>{t('orders.scheduled')}<b>{new Date(o.scheduled_for+'Z').toLocaleString()}</b></span>}</div><div className="order-price">{money(o.calculated_price,o.currency||currency)}</div></article>)}</div></section>}
function ProfilePage({t,session,locale,setLocale,currency,setCurrency,goto}:any){const changeCurrency=async(next:string)=>{const value=next.toUpperCase();setCurrency(value);try{await api.setCurrency(value);notify('success')}catch{notify('error')}};return <section><div className="profile-card"><div className="avatar">{(session.user.firstName||'C')[0]}</div><div className="grow"><h2>{session.user.firstName}</h2><p>{session.user.username?'@'+session.user.username:t('common.telegramUser')}</p><small>{t('profile.role')}: {t((`role.${session.user.role}` as TranslationKey))}</small></div></div><div className="settings-card"><label><Globe2/><span>{t('profile.language')}</span><select value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="uk">{localeNames.uk}</option><option value="pl">{localeNames.pl}</option><option value="en">{localeNames.en}</option></select></label><label><Gem/><span>{t('profile.currency')}</span><select value={currency} onChange={e=>changeCurrency(e.target.value)}><option>PLN</option><option>USD</option><option>UAH</option></select></label><button className="profile-action" onClick={()=>goto('orders')}><ClipboardList/><span><b>{t('profile.requests')}</b><small>{t('profile.requestsHint')}</small></span><ChevronRight/></button><button className="profile-action" onClick={()=>openBot()}><MessageCircle/><span><b>{t('profile.chat')}</b><small>{t('profile.chatHint')}</small></span><ChevronRight/></button></div></section>}
const previewFx:Record<string,Record<string,number>>={PLN:{PLN:1,USD:.26,UAH:11.1},USD:{USD:1,PLN:3.85,UAH:42.7},UAH:{UAH:1,PLN:.09,USD:.0234}};
const convertPreview=(v:number,from:string,to:string)=>Number(v||0)*(previewFx[from]?.[to]||1);
const money=(v:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c||'PLN',maximumFractionDigits:2}).format(Number(v||0));
